#!/usr/bin/env python3
"""Deterministic registry/code-generation pipeline for CMP reengineering beta11.

Standard-library only. Run from anywhere:
    python3 tools/generate_registry.py
    python3 tools/generate_registry.py --check

Generated game files:
- common/scripted_guis/cmp_fleet_builder_sgui.txt
- common/scripted_effects/cmp_fleet_builder_effects.txt
- common/scripted_triggers/cmp_provider_triggers.txt
- generated/registry_manifest.json
- generated/fleet_ship_selector.gui.txt
- generated/registry_reference.md
- generated/registry_reference_ru.md

The Fleet Builder ship selector block inside gui/main/sakuya_main.gui is also
regenerated between explicit markers.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REG = ROOT / "registry"
GENERATED = ROOT / "generated"
GUI_PATH = ROOT / "gui/main/sakuya_main.gui"
SGUI_PATH = ROOT / "common/scripted_guis/cmp_fleet_builder_sgui.txt"
EFFECT_PATH = ROOT / "common/scripted_effects/cmp_fleet_builder_effects.txt"
PROVIDER_TRIGGER_PATH = ROOT / "common/scripted_triggers/cmp_provider_triggers.txt"

BEGIN = "# CMP_REGISTRY_BEGIN fleet_ship_selector"
END = "# CMP_REGISTRY_END fleet_ship_selector"
HEADER = "# AUTO-GENERATED by tools/generate_registry.py. DO NOT EDIT BY HAND.\n"


def load(name: str):
    return json.loads((REG / name).read_text(encoding="utf-8"))


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def write_bom(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8-sig")


def write_plain(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def technology_gate(tech: str | None) -> str:
    return "always = yes" if not tech else f"has_technology_researched = {tech}"




def provider_gate(ship: dict) -> str:
    provider = ship.get("provider", "vanilla")
    if provider == "vanilla":
        return "always = yes"
    if provider == "tech_res":
        return "cmp_provider_tech_res_active = yes"
    return "always = no"


def create_ship_lines(ship_type: str, count: int, indent: str = "        ", target_scope: str = "cmp_fleet_builder_target") -> list[str]:
    return [f"{indent}create_ship = {{ type = ship_type:{ship_type} fleet = scope:{target_scope} }}" for _ in range(count)]


def generate_provider_triggers(providers: list[dict]) -> str:
    lines = [HEADER.rstrip(), "# Provider adapters. Current beta11 stack requires CMF + Tech & Res."]
    for p in providers:
        trig = p.get("detection_trigger")
        if not trig:
            continue
        sid = p["id"].replace("-", "_")
        lines.append(f"cmp_provider_{sid}_active = {{ {trig} = yes }}")
    lines.append("")
    return "\n".join(lines)


def generate_fleet_sgui(ships: list[dict], fleet: dict) -> str:
    lines = [HEADER.rstrip(), "# Fleet Builder generated from registry/ships.json + registry/fleet_builder.json"]
    for idx, ship in enumerate(ships, 1):
        sid, tech = ship["id"], ship.get("unlock_technology")
        gate = technology_gate(tech)
        pgate = provider_gate(ship)
        lines.append(f"cmp_fleet_builder_ship_{sid}_available = {{ scope = country is_shown = {{ {pgate} {gate} }} }}")
        lines.append(f"cmp_fleet_builder_ship_{sid}_selected = {{ scope = country is_shown = {{ var:cmp_fleet_builder_ship_index = {idx} }} }}")
        lines.append(f"cmp_fleet_builder_select_{sid} = {{ scope = country is_valid = {{ {pgate} {gate} }} effect = {{ cmp_fleet_builder_select_{sid}_effect = yes }} }}")
    for amount in fleet["amounts"]:
        value, idx = amount["value"], amount["index"]
        lines.append(f"cmp_fleet_builder_amount_{value}_selected = {{ scope = country is_shown = {{ var:cmp_fleet_builder_amount_index = {idx} }} }}")
        lines.append(f"cmp_fleet_builder_select_amount_{value} = {{ scope = country is_valid = {{ always = yes }} effect = {{ cmp_fleet_builder_select_amount_{value}_effect = yes }} }}")

    # Legacy marker-derived target check remains for hidden fallback surfaces.
    lines += [
        "cmp_fleet_builder_target_ready = {",
        "    scope = country",
        "    is_shown = { cmp_military_target_fleet_ready_trigger = yes }",
        "}",
        "cmp_fleet_builder_has_ship = { scope = country is_shown = { has_variable = cmp_fleet_builder_ship_index } }",
        "cmp_fleet_builder_has_amount = { scope = country is_shown = { has_variable = cmp_fleet_builder_amount_index } }",
        # pre2.4 candidate endpoint: GUI must already prove GetSelectedFormation.IsFleet; ScriptedGui only validates ownership and operation prerequisites.
        "cmp_fleet_builder_apply_native = {",
        "    scope = military_formation",
        "    is_valid = {",
        "        owner = {",
        "            is_player = yes",
        "            has_variable = cmp_fleet_builder_ship_index",
        "            has_variable = cmp_fleet_builder_amount_index",
        "            OR = {",
    ]
    for idx, ship in enumerate(ships, 1):
        lines.append(f"                AND = {{ var:cmp_fleet_builder_ship_index = {idx} {provider_gate(ship)} {technology_gate(ship.get('unlock_technology'))} }}")
    lines += [
        "            }",
        "        }",
        # Empty fleets are explicitly valid. A fleet with any ship currently in battle is blocked.
        "        NOT = { any_scope_ship = { is_in_battle = yes } }",
        "    }",
        "    effect = { cmp_fleet_builder_apply_native_effect = yes }",
        "}",
        # Legacy country-root marker path retained but no longer used by the Workspace production button.
        "cmp_fleet_builder_apply = {",
        "    scope = country",
        "    is_valid = {",
        "        has_variable = cmp_fleet_builder_ship_index",
        "        has_variable = cmp_fleet_builder_amount_index",
        "        cmp_military_target_fleet_ready_trigger = yes",
        "        OR = {",
    ]
    for idx, ship in enumerate(ships, 1):
        lines.append(f"            AND = {{ var:cmp_fleet_builder_ship_index = {idx} {provider_gate(ship)} {technology_gate(ship.get('unlock_technology'))} }}")
    lines += [
        "        }",
        "    }",
        "    effect = { cmp_fleet_builder_apply_effect = yes }",
        "}",
        "cmp_fleet_builder_clear = { scope = country is_valid = { always = yes } effect = { cmp_fleet_builder_clear_selection_effect = yes } }",
        "cmp_fleet_builder_result_created = { scope = country is_shown = { var:cmp_fleet_builder_result = 1 } }",
        "cmp_fleet_builder_result_preset = { scope = country is_shown = { var:cmp_fleet_builder_result = 3 } }",
        "cmp_fleet_builder_result_taskforce = { scope = country is_shown = { var:cmp_fleet_builder_result = 4 } }",
        "cmp_fleet_builder_result_failed = { scope = country is_shown = { var:cmp_fleet_builder_result = 2 } }",
    ]
    common_target = "cmp_military_target_fleet_ready_trigger = yes"
    for preset in fleet["presets"]:
        req = " ".join(f"has_technology_researched = {x}" for x in preset["requires"])
        lines.append(f"cmp_fleet_builder_preset_{preset['id']} = {{ scope = country is_valid = {{ cmp_provider_tech_res_active = yes {common_target} {req} }} effect = {{ cmp_fleet_builder_preset_{preset['id']}_effect = yes }} }}")
    lines += [
        "cmp_fleet_taskforce_ready = {",
        "    scope = country",
        "    is_shown = {",
        "        cmp_provider_tech_res_active = yes",
        "        cmp_military_target_fleet_ready_trigger = yes",
        "        has_variable = cmp_army_amphib_amount_index",
        "        OR = { has_technology_researched = amphibious_warfare has_technology_researched = high_performance_apparel }",
        "        any_scope_state = { has_decree = decree_sakuya_mark_state has_port_state = yes }",
        "        OR = { has_technology_researched = modern_naval_doctrine has_technology_researched = modern_battleships }",
        "    }",
        "}",
        "cmp_fleet_taskforce_prepare = { scope = country is_valid = { cmp_provider_tech_res_active = yes cmp_military_target_fleet_ready_trigger = yes has_variable = cmp_army_amphib_amount_index OR = { has_technology_researched = amphibious_warfare has_technology_researched = high_performance_apparel } any_scope_state = { has_decree = decree_sakuya_mark_state has_port_state = yes } OR = { has_technology_researched = modern_naval_doctrine has_technology_researched = modern_battleships } } effect = { cmp_fleet_taskforce_prepare_effect = yes } }",
        "",
    ]
    return "\n".join(lines)


def generate_fleet_effects(ships: list[dict], fleet: dict) -> str:
    by_id = {s["id"]: s for s in ships}
    lines = [HEADER.rstrip(), "# Fleet Builder generated from registry/ships.json + registry/fleet_builder.json"]
    lines.append("cmp_fleet_builder_clear_result_effect = { remove_variable = cmp_fleet_builder_result }")
    lines.append("cmp_fleet_builder_clear_selection_effect = { remove_variable = cmp_fleet_builder_ship_index remove_variable = cmp_fleet_builder_amount_index remove_variable = cmp_fleet_builder_result }")
    for idx, ship in enumerate(ships, 1):
        lines.append(f"cmp_fleet_builder_select_{ship['id']}_effect = {{ set_variable = {{ name = cmp_fleet_builder_ship_index value = {idx} }} cmp_fleet_builder_clear_result_effect = yes }}")
    for amount in fleet["amounts"]:
        lines.append(f"cmp_fleet_builder_select_amount_{amount['value']}_effect = {{ set_variable = {{ name = cmp_fleet_builder_amount_index value = {amount['index']} }} cmp_fleet_builder_clear_result_effect = yes }}")
    lines += [
        "cmp_fleet_builder_apply_native_effect = {",
        "    save_scope_as = cmp_fleet_builder_native_target",
        "    owner = {",
        "        remove_variable = cmp_fleet_builder_result",
    ]
    for ship_index, ship in enumerate(ships, 1):
        for amount in fleet["amounts"]:
            lines += [
                "        if = {",
                f"            limit = {{ {provider_gate(ship)} var:cmp_fleet_builder_ship_index = {ship_index} var:cmp_fleet_builder_amount_index = {amount['index']} {technology_gate(ship.get('unlock_technology'))} }}",
            ]
            lines += create_ship_lines(ship["ship_type"], amount["value"], indent="            ", target_scope="cmp_fleet_builder_native_target")
            lines += ["            set_variable = { name = cmp_fleet_builder_result value = 1 }", "        }"]
    lines += [
        "        if = { limit = { NOT = { var:cmp_fleet_builder_result = 1 } } set_variable = { name = cmp_fleet_builder_result value = 2 } }",
        "    }",
        "    clear_saved_scope = cmp_fleet_builder_native_target",
        "}",
        "cmp_fleet_builder_resolve_target_effect = {",
        "    clear_saved_scope = cmp_fleet_builder_target",
        "    ordered_military_formation = {",
        "        limit = {",
        "            is_fleet = yes",
        "            has_variable = cmp_military_target_fleet",
        "            any_scope_ship = { is_in_battle = no }",
        "        }",
        "        position = 0",
        "        check_range_bounds = no",
        "        save_scope_as = cmp_fleet_builder_target",
        "    }",
        "}",
        "cmp_fleet_builder_apply_effect = {",
        "    remove_variable = cmp_fleet_builder_result",
        "    cmp_fleet_builder_resolve_target_effect = yes",
    ]
    for ship_index, ship in enumerate(ships, 1):
        for amount in fleet["amounts"]:
            lines += [
                "    if = {",
                f"        limit = {{ {provider_gate(ship)} var:cmp_fleet_builder_ship_index = {ship_index} var:cmp_fleet_builder_amount_index = {amount['index']} exists = scope:cmp_fleet_builder_target {technology_gate(ship.get('unlock_technology'))} }}",
            ]
            lines += create_ship_lines(ship["ship_type"], amount["value"])
            lines += ["        set_variable = { name = cmp_fleet_builder_result value = 1 }", "    }"]
    lines += [
        "    if = { limit = { NOT = { var:cmp_fleet_builder_result = 1 } } set_variable = { name = cmp_fleet_builder_result value = 2 } }",
        "}",
    ]
    for preset in fleet["presets"]:
        req = " ".join(f"has_technology_researched = {x}" for x in preset["requires"])
        lines += [
            f"cmp_fleet_builder_preset_{preset['id']}_effect = {{",
            "    remove_variable = cmp_fleet_builder_result",
            "    cmp_fleet_builder_resolve_target_effect = yes",
            "    if = {",
            f"        limit = {{ cmp_provider_tech_res_active = yes exists = scope:cmp_fleet_builder_target {req} }}",
        ]
        for sid, count in preset["ships"].items():
            lines += create_ship_lines(by_id[sid]["ship_type"], count)
        lines += [
            "        set_variable = { name = cmp_fleet_builder_result value = 3 }",
            "    }",
            "    if = { limit = { NOT = { var:cmp_fleet_builder_result = 3 } } set_variable = { name = cmp_fleet_builder_result value = 2 } }",
            "}",
        ]
    lines += [
        "cmp_fleet_taskforce_prepare_effect = {",
        "    remove_variable = cmp_fleet_builder_result",
        "    cmp_fleet_builder_resolve_target_effect = yes",
        "    if = {",
        "        limit = {",
        "            cmp_provider_tech_res_active = yes",
        "            exists = scope:cmp_fleet_builder_target",
        "            has_variable = cmp_army_amphib_amount_index",
        "            OR = { has_technology_researched = amphibious_warfare has_technology_researched = high_performance_apparel }",
        "            any_scope_state = { has_decree = decree_sakuya_mark_state has_port_state = yes }",
        "            OR = { has_technology_researched = modern_naval_doctrine has_technology_researched = modern_battleships }",
        "        }",
    ]
    for group in fleet["amphibious_support"]:
        req = " ".join(f"has_technology_researched = {x}" for x in group["requires"])
        lines += ["        if = {", f"            limit = {{ {req} }}"]
        for sid, count in group["ships"].items():
            lines += create_ship_lines(by_id[sid]["ship_type"], count, indent="            ")
        lines += ["        }"]
    lines += [
        "        cmp_army_amphib_apply_effect = yes",
        "        if = { limit = { var:cmp_army_amphib_result = 1 } set_variable = { name = cmp_fleet_builder_result value = 4 } }",
        "    }",
        "    if = { limit = { NOT = { var:cmp_fleet_builder_result = 4 } } set_variable = { name = cmp_fleet_builder_result value = 2 } }",
        "}",
        "",
    ]
    return "\n".join(lines)


def generate_ship_gui(ships: list[dict]) -> str:
    # beta14 accessibility layout: two wide ship buttons per row instead of five tiny buttons.
    lines = [BEGIN]
    for row_start in range(0, len(ships), 2):
        row = ships[row_start:row_start+2]
        lines.append("                    widget = { size = { 548 50 } hbox = { spacing = 8")
        for ship in row:
            sid = ship["id"]
            loc = ship["loc_key"]
            lines += [
                "                        widget = { size = { 268 48 }",
                f"                            button_standard = {{ size = {{ 268 48 }} tooltip = \"CMP_FLEET_SHIP_LOCKED_TT\" enabled = \"[GetScriptedGui('cmp_fleet_builder_ship_{sid}_available').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]\" visible = \"[Not(GetScriptedGui('cmp_fleet_builder_ship_{sid}_selected').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End))]\" onclick = \"[GetScriptedGui('cmp_fleet_builder_select_{sid}').Execute(GuiScope.SetRoot(GetPlayer.MakeScope).End)]\" blockoverride \"primary_visible\" {{}} blockoverride \"primary_texture\" {{ texture = \"gfx/interface/buttons/expand_button_bg_dropdown.dds\" color = {{ 0.75 0.55 0.62 1 }} }} textbox = {{ size = {{ 258 42 }} parentanchor = center autoresize = no maximumsize = {{ 258 42 }} fontsize = 14 fontsize_min = 11 align = center|nobaseline elide = right text = \"{loc}\" }} }}",
                f"                            button_standard = {{ size = {{ 268 48 }} tooltip = \"CMP_FLEET_SHIP_LOCKED_TT\" visible = \"[GetScriptedGui('cmp_fleet_builder_ship_{sid}_selected').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]\" onclick = \"[GetScriptedGui('cmp_fleet_builder_select_{sid}').Execute(GuiScope.SetRoot(GetPlayer.MakeScope).End)]\" blockoverride \"primary_visible\" {{}} blockoverride \"primary_texture\" {{ texture = \"gfx/interface/buttons/expand_button_bg_dropdown.dds\" color = {{ 0.45 0.9 0.5 1 }} }} textbox = {{ size = {{ 258 42 }} parentanchor = center autoresize = no maximumsize = {{ 258 42 }} fontsize = 14 fontsize_min = 11 align = center|nobaseline elide = right text = \"{loc}\" }} }}",
                "                        }",
            ]
        lines.append("                    } }")
    lines.append(END)
    return "\n".join(lines)


def patch_gui(gui: str, block: str) -> str:
    if BEGIN in gui and END in gui:
        pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
        return pattern.sub(block, gui, count=1)
    anchor = '                widget = { size = { 548 40 } hbox = { spacing = 5\n'
    start = gui.find(anchor, gui.find('text = "CMP_FLEET_SHIP_TITLE"'))
    if start < 0:
        raise RuntimeError("Fleet ship selector anchor not found")
    content_start = start + len(anchor)
    next_anchor = '                } }\n                widget = { size = { 548 40 } hbox = { spacing = 8\n'
    end = gui.find(next_anchor, content_start)
    if end < 0:
        raise RuntimeError("Fleet amount selector anchor not found")
    return gui[:content_start] + block + "\n" + gui[end:]


def validate_registries(providers, buildings, units, ships, resources, fleet, operations):
    errors=[]
    provider_ids={p['id'] for p in providers}
    def unique(items, key, label):
        vals=[x[key] for x in items]
        dup=sorted({x for x in vals if vals.count(x)>1})
        if dup: errors.append(f"duplicate {label}: {dup}")
    unique(buildings,'id','building id'); unique(buildings,'building_type','building type')
    unique(units,'id','unit id'); unique(units,'unit_type','unit type')
    unique(ships,'id','ship id'); unique(ships,'ship_type','ship type')
    unique(resources,'id','resource id'); unique(resources,'building_type','resource building type')
    unique(operations,'id','operation id')
    for label, items in [('building',buildings),('unit',units),('ship',ships),('resource',resources)]:
        for x in items:
            if x.get('provider') not in provider_ids:
                errors.append(f"{label} {x['id']} references unknown provider {x.get('provider')}")
    ship_ids={s['id'] for s in ships}
    for preset in fleet['presets']:
        for sid in preset['ships']:
            if sid not in ship_ids: errors.append(f"preset {preset['id']} unknown ship {sid}")
    for group in fleet['amphibious_support']:
        for sid in group['ships']:
            if sid not in ship_ids: errors.append(f"amphibious support unknown ship {sid}")
    values=[x['value'] for x in fleet['amounts']]
    indices=[x['index'] for x in fleet['amounts']]
    if len(values)!=len(set(values)) or len(indices)!=len(set(indices)):
        errors.append('fleet amounts have duplicate values/indices')
    return errors


def reference_markdown(counts: dict, ru: bool=False) -> str:
    if ru:
        return f"""# CMP beta11 — Registry / Code Generation\n\nBeta11 вводит декларативный слой данных перед дальнейшим рефакторингом CMP.\n\n- Провайдеры: **{counts['providers']}**\n- Здания Staffing Assistant: **{counts['buildings']}**\n- Типы сухопутных юнитов: **{counts['units']}**\n- Типы кораблей: **{counts['ships']}**\n- Ресурсы Tech & Res: **{counts['resources']}**\n- Зарегистрированные операции: **{counts['operations']}**\n\n## Что уже генерируется\n\n`cmp_fleet_builder_sgui.txt`, `cmp_fleet_builder_effects.txt`, адаптеры provider detection и строка выбора кораблей в `sakuya_main.gui` генерируются из JSON registry.\n\nЭто первый production-путь codegen. Следующий этап (beta12) сможет использовать те же registry для Regions/Buildings/Resources/Staffing.\n"""
    return f"""# CMP beta11 — Registry / Code Generation\n\nBeta11 introduces a declarative data layer before the next CMP refactoring stages.\n\n- Providers: **{counts['providers']}**\n- Staffing Assistant buildings: **{counts['buildings']}**\n- Land unit types: **{counts['units']}**\n- Ship types: **{counts['ships']}**\n- Tech & Res resources: **{counts['resources']}**\n- Registered operations: **{counts['operations']}**\n\n## Production codegen path\n\n`cmp_fleet_builder_sgui.txt`, `cmp_fleet_builder_effects.txt`, provider-detection adapters and the Fleet Builder ship selector in `sakuya_main.gui` are generated from the JSON registries.\n\nThis is the first production codegen path. Beta12 can consume the same registries for Regions/Buildings/Resources/Staffing.\n"""


def build_outputs():
    providers=load('providers.json')['providers']
    buildings=load('buildings.json')['buildings']
    units=load('land_units.json')['units']
    ships=load('ships.json')['ships']
    resources=load('resources.json')['resources']
    fleet=load('fleet_builder.json')
    operations=load('operations.json')['operations']
    errors=validate_registries(providers,buildings,units,ships,resources,fleet,operations)
    if errors:
        raise RuntimeError("Registry validation failed:\n- " + "\n- ".join(errors))
    sgui=generate_fleet_sgui(ships,fleet)
    effects=generate_fleet_effects(ships,fleet)
    providers_txt=generate_provider_triggers(providers)
    ship_gui=generate_ship_gui(ships)
    gui=GUI_PATH.read_text(encoding='utf-8-sig')
    patched_gui=patch_gui(gui,ship_gui)
    counts={'providers':len(providers),'buildings':len(buildings),'units':len(units),'ships':len(ships),'resources':len(resources),'operations':len(operations)}
    manifest={
        'schema_version':1,
        'generator':'tools/generate_registry.py',
        'counts':counts,
        'generated':{
            str(SGUI_PATH.relative_to(ROOT)):sha256_text(sgui),
            str(EFFECT_PATH.relative_to(ROOT)):sha256_text(effects),
            str(PROVIDER_TRIGGER_PATH.relative_to(ROOT)):sha256_text(providers_txt),
            'generated/fleet_ship_selector.gui.txt':sha256_text(ship_gui),
        },
        'codegen_scope':['fleet_builder_sgui','fleet_builder_effects','fleet_ship_selector_gui','provider_detection_adapters'],
        'next_consumers':['beta12_regions_buildings_resources_staffing','beta17_army_final','beta18_navy_final'],
    }
    return {
        SGUI_PATH:sgui,
        EFFECT_PATH:effects,
        PROVIDER_TRIGGER_PATH:providers_txt,
        GENERATED/'fleet_ship_selector.gui.txt':ship_gui+'\n',
        GENERATED/'registry_manifest.json':json.dumps(manifest,indent=2,ensure_ascii=False)+'\n',
        GENERATED/'registry_reference.md':reference_markdown(counts,False),
        GENERATED/'registry_reference_ru.md':reference_markdown(counts,True),
        GUI_PATH:patched_gui,
    }, manifest


def normalized_read(path: Path) -> str:
    return path.read_text(encoding='utf-8-sig')


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--check',action='store_true',help='validate registries and verify generated outputs are current')
    args=ap.parse_args()
    outputs, manifest=build_outputs()
    if args.check:
        stale=[]
        for path, expected in outputs.items():
            if not path.exists():
                stale.append(f"missing: {path.relative_to(ROOT)}")
                continue
            actual=normalized_read(path) if path.suffix in {'.txt','.gui'} or path.name=='sakuya_main.gui' else path.read_text(encoding='utf-8')
            if actual != expected:
                stale.append(f"stale: {path.relative_to(ROOT)}")
        if stale:
            print('REGISTRY_CHECK_FAIL')
            for s in stale: print(s)
            return 1
        print('REGISTRY_CHECK_PASS', json.dumps(manifest['counts'],sort_keys=True))
        return 0
    for path, text in outputs.items():
        if path in {SGUI_PATH,EFFECT_PATH,PROVIDER_TRIGGER_PATH,GUI_PATH}:
            write_bom(path,text)
        else:
            write_plain(path,text)
    print('REGISTRY_GENERATE_PASS', json.dumps(manifest['counts'],sort_keys=True))
    return 0

if __name__=='__main__':
    sys.exit(main())
