#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, re, sys, hashlib
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
REG=ROOT/'registry'
GUI=ROOT/'gui/main/sakuya_main.gui'
SGUI=ROOT/'common/scripted_guis/cmp_regions2_sgui.txt'
EFFECT=ROOT/'common/scripted_effects/cmp_regions2_effects.txt'
TRIGGER=ROOT/'common/scripted_triggers/cmp_regions2_triggers.txt'
STAFF_SGUI=ROOT/'common/scripted_guis/cmp_staffing_adaptive_sgui.txt'
STAFF_EFFECT=ROOT/'common/scripted_effects/cmp_staffing_adaptive_effects.txt'
STAFF_TRIGGER=ROOT/'common/scripted_triggers/cmp_staffing_adaptive_triggers.txt'
GENERATED=ROOT/'generated'
BEGIN='# CMP_REGIONS2_BEGIN assistant_submode'
END='# CMP_REGIONS2_END assistant_submode'
ADAPT_BEGIN='# CMP_STAFF_ADAPTIVE_BEGIN generated_controls'
ADAPT_END='# CMP_STAFF_ADAPTIVE_END generated_controls'
HEADER='# AUTO-GENERATED by tools/generate_regions2.py. DO NOT EDIT BY HAND.\n'

def load(name): return json.loads((REG/name).read_text(encoding='utf-8'))
def sha(t): return hashlib.sha256(t.encode()).hexdigest()
def wplain(p,t): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(t,encoding='utf-8')
def wbom(p,t): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(t,encoding='utf-8-sig')

def selection_condition(item):
    terms=[f"has_variable = {item['selection_variable']}"]
    if item.get('legacy_selection_variable'):
        terms.append(f"has_variable = {item['legacy_selection_variable']}")
    return 'OR = { ' + ' '.join(terms) + ' }' if len(terms)>1 else terms[0]

def selection_or(items):
    return 'OR = { ' + ' '.join(selection_condition(x) for x in items) + ' }'

def exact_gate(rootvar, values):
    return 'OR = { ' + ' '.join(f"var:{rootvar} = {i+1}" for i,_ in enumerate(values)) + ' }'

def techres_trait_maps(resources):
    return {r['building_type']:[t['trait'] for t in r.get('tiers',[])] for r in resources}

def generate_triggers(buildings, resources, cfg):
    b_by_id={b['id']:b for b in buildings}
    rb=[b_by_id[x] for x in cfg['resource_capable_buildings']]
    lines=[HEADER.rstrip(), '# Regions & Buildings 2.1 registry triggers']
    lines += [
      f"cmp_regions2_has_selected_building = {{ {selection_or(buildings)} }}",
      f"cmp_regions2_has_selected_resource = {{ {selection_or(rb)} }}",
      "cmp_regions2_mode_building = { OR = { NOT = { has_variable = cmp_regions2_mode_index } var:cmp_regions2_mode_index = 1 } }",
      "cmp_regions2_mode_resource = { var:cmp_regions2_mode_index = 2 }",
      "cmp_regions2_mode_preset = { var:cmp_regions2_mode_index = 3 }",
      "cmp_regions2_configuration_ready = {",
      "  OR = {",
      "    AND = { cmp_regions2_mode_building = yes cmp_regions2_has_selected_building = yes has_variable = cmp_regions2_operation_index OR = { var:cmp_regions2_operation_index = 3 has_variable = cmp_regions2_amount_index } }",
      "    AND = { cmp_regions2_mode_resource = yes cmp_regions2_has_selected_resource = yes has_variable = cmp_regions2_operation_index OR = { var:cmp_regions2_operation_index = 3 has_variable = cmp_regions2_amount_index } }",
      "    AND = { cmp_regions2_mode_preset = yes has_variable = cmp_regions2_preset_index }",
      "  }",
      "}",
      "cmp_regions2_has_player_marked_target = { any_scope_state = { has_decree = decree_sakuya_mark_state } }",
      "cmp_regions2_has_incorporated_target = { any_scope_state = { is_incorporated = yes } }",
      "cmp_regions2_has_foreign_marked_target = { any_country = { has_variable = sakuya_mark_country_target } any_state = { has_variable = sakuya_mark_foreign_state_target owner = { has_variable = sakuya_mark_country_target } } }",
      ""
    ]
    return '\n'.join(lines)

def generate_regions_sgui(buildings, cfg):
    amounts=cfg['building_amounts']; presets=cfg['presets']; resource_ids=set(cfg['resource_capable_buildings'])
    L=[HEADER.rstrip(),'# Regions & Buildings 2.1 GUI endpoints']
    L += [
      "cmp_regions2_has_selected_building_check = { scope = country is_shown = { cmp_regions2_has_selected_building = yes } }",
      "cmp_regions2_mode_building_selected = { scope = country is_shown = { cmp_regions2_mode_building = yes } }",
      "cmp_regions2_mode_resource_selected = { scope = country is_shown = { cmp_regions2_mode_resource = yes } }",
      "cmp_regions2_mode_preset_selected = { scope = country is_shown = { cmp_regions2_mode_preset = yes } }",
      "cmp_regions2_select_mode_building = { scope = country is_valid = { always = yes } effect = { cmp_regions2_select_mode_building_effect = yes } }",
      "cmp_regions2_select_mode_resource = { scope = country is_valid = { cmp_regions2_has_selected_resource = yes } effect = { cmp_regions2_select_mode_resource_effect = yes } }",
      "cmp_regions2_select_mode_preset = { scope = country is_valid = { always = yes } effect = { cmp_regions2_select_mode_preset_effect = yes } }",
    ]
    for b in buildings:
        cond=selection_condition(b)
        L.append(f"cmp_regions2_building_{b['id']}_selected = {{ scope = country is_shown = {{ {cond} }} }}")
        L.append(f"cmp_regions2_select_building_{b['id']} = {{ scope = country is_valid = {{ always = yes }} effect = {{ cmp_regions2_select_building_{b['id']}_effect = yes }} }}")
        if b['id'] in resource_ids:
            L.append(f"cmp_regions2_select_resource_{b['id']} = {{ scope = country is_valid = {{ always = yes }} effect = {{ cmp_regions2_select_resource_{b['id']}_effect = yes }} }}")
    for i,name in enumerate(['add','set','remove'],1):
        L.append(f"cmp_regions2_operation_{name}_selected = {{ scope = country is_shown = {{ var:cmp_regions2_operation_index = {i} }} }}")
        L.append(f"cmp_regions2_select_operation_{name} = {{ scope = country is_valid = {{ NOT = {{ cmp_regions2_mode_preset = yes }} }} effect = {{ cmp_regions2_select_operation_{name}_effect = yes }} }}")
    for i,a in enumerate(amounts,1):
        L.append(f"cmp_regions2_amount_{a}_selected = {{ scope = country is_shown = {{ var:cmp_regions2_amount_index = {i} }} }}")
        L.append(f"cmp_regions2_select_amount_{a} = {{ scope = country is_valid = {{ NOT = {{ cmp_regions2_mode_preset = yes }} NOT = {{ var:cmp_regions2_operation_index = 3 }} }} effect = {{ cmp_regions2_select_amount_{a}_effect = yes }} }}")
    for i,p in enumerate(presets,1):
        L.append(f"cmp_regions2_preset_{p['id']}_selected = {{ scope = country is_shown = {{ var:cmp_regions2_preset_index = {i} }} }}")
        L.append(f"cmp_regions2_select_preset_{p['id']} = {{ scope = country is_valid = {{ cmp_regions2_mode_preset = yes }} effect = {{ cmp_regions2_select_preset_{p['id']}_effect = yes }} }}")
    L += [
      "cmp_regions2_can_player_marked = { scope = country is_shown = { cmp_regions2_configuration_ready = yes cmp_regions2_has_player_marked_target = yes } }",
      "cmp_regions2_can_incorporated = { scope = country is_shown = { cmp_regions2_configuration_ready = yes cmp_regions2_has_incorporated_target = yes } }",
      "cmp_regions2_can_foreign = { scope = country is_shown = { cmp_regions2_configuration_ready = yes cmp_regions2_has_foreign_marked_target = yes } }",
      "cmp_regions2_apply_player_marked = { scope = country is_valid = { cmp_regions2_configuration_ready = yes cmp_regions2_has_player_marked_target = yes } effect = { cmp_regions2_apply_player_marked_effect = yes } }",
      "cmp_regions2_apply_incorporated = { scope = country is_valid = { cmp_regions2_configuration_ready = yes cmp_regions2_has_incorporated_target = yes } effect = { cmp_regions2_apply_incorporated_effect = yes } }",
      "cmp_regions2_apply_foreign = { scope = country is_valid = { cmp_regions2_configuration_ready = yes cmp_regions2_has_foreign_marked_target = yes } effect = { cmp_regions2_apply_foreign_effect = yes } }",
      "cmp_regions2_clear = { scope = country is_valid = { always = yes } effect = { cmp_regions2_clear_effect = yes } }",
      "cmp_regions2_result_success = { scope = country is_shown = { var:cmp_regions2_result = 1 } }",
      "cmp_regions2_result_no_target = { scope = country is_shown = { var:cmp_regions2_result = 2 } }",
      "cmp_regions2_result_partial = { scope = country is_shown = { var:cmp_regions2_result = 3 } }",
      "cmp_regions2_result_add_limit = { scope = country is_shown = { var:cmp_regions2_result = 4 } }",
      "cmp_regions2_result_failed = { scope = country is_shown = { var:cmp_regions2_result = 5 } }",
      "cmp_regions2_result_blocked = { scope = country is_shown = { var:cmp_regions2_result = 6 } }",
      "cmp_regions2_result_unsafe = { scope = country is_shown = { var:cmp_regions2_result = 7 } }",
      ""
    ]
    return '\n'.join(L)

def generate_add_one_exact_effect(maxlevel):
    L=["cmp_regions2_build_add_one_exact_effect = {"]
    for current in range(maxlevel+1):
        kw='if' if current==0 else 'else_if'; new=current+1
        L += [f"  {kw} = {{",f"    limit = {{ state_has_building_type_levels = {{ target = bt:$BUILDING$ value = {current} }} }}",f"    create_building = {{ building = $BUILDING$ level = {new} }}",f"    if = {{ limit = {{ state_has_building_type_levels = {{ target = bt:$BUILDING$ value = {new} }} }} root = {{ set_variable = cmp_regions2_any_success }} }}",f"    else = {{ root = {{ set_variable = cmp_regions2_any_failed }} set_variable = cmp_regions2_state_blocked }}","  }"]
    L += ["  else = { root = { set_variable = cmp_regions2_any_overflow } set_variable = cmp_regions2_state_blocked }","}"]
    return '\n'.join(L)

def generate_add_effect(delta):
    L=[f"cmp_regions2_build_add_{delta}_effect = {{"]
    for _ in range(delta):
        L.append("  cmp_regions2_build_add_one_guarded_effect = { BUILDING = $BUILDING$ }")
    L += ["}"]
    return '\n'.join(L)

def generate_set_effect(target, maxlevel):
    L=[f"cmp_regions2_build_set_{target}_effect = {{"]
    for current in range(maxlevel+1):
        kw='if' if current==0 else 'else_if'
        L += [f"  {kw} = {{",f"    limit = {{ state_has_building_type_levels = {{ target = bt:$BUILDING$ value = {current} }} }}"]
        if current < target:
            for _ in range(target-current):
                L.append("    cmp_regions2_build_add_one_guarded_effect = { BUILDING = $BUILDING$ }")
            L.append(f"    if = {{ limit = {{ state_has_building_type_levels = {{ target = bt:$BUILDING$ value = {target} }} }} root = {{ set_variable = cmp_regions2_any_success }} }}")
        elif current == target:
            L.append("    root = { set_variable = cmp_regions2_any_success }")
        else:
            L.append("    root = { set_variable = cmp_regions2_any_unsafe }")
        L.append("  }")
    L += ["  else = { root = { set_variable = cmp_regions2_any_overflow } }","}"]
    return '\n'.join(L)

def remove_trait_lines(traits, indent='    '):
    return [f"{indent}state_region = {{ if = {{ limit = {{ has_state_trait = {t} }} remove_state_trait = {t} }} }}" for t in traits]

def generate_regions_effects(buildings, resources, cfg):
    amounts=cfg['building_amounts']; maxlevel=cfg['add_exact_max_existing_level']; presets=cfg['presets']
    all_add_amounts=sorted(set(amounts) | {delta for p in presets for delta in p['buildings'].values()})
    b_by_id={b['id']:b for b in buildings}; res_by_bt={r['building_type']:r for r in resources}
    rb={b_by_id[x]['building_type'] for x in cfg['resource_capable_buildings']}
    L=[HEADER.rstrip(), '# Regions & Buildings 2.1 effects: guarded availability, independent selection, safe SET']
    L += [
      "cmp_regions2_clear_result_effect = { remove_variable = cmp_regions2_result remove_variable = cmp_regions2_any_success remove_variable = cmp_regions2_any_failed remove_variable = cmp_regions2_any_overflow remove_variable = cmp_regions2_any_blocked remove_variable = cmp_regions2_any_unsafe }",
      "cmp_regions2_clear_new_building_selection_effect = {",
    ]
    for b in buildings: L.append(f"  remove_variable = {b['selection_variable']}")
    L += [
      "}",
      "cmp_regions2_clear_building_selection_effect = { cmp_regions2_clear_new_building_selection_effect = yes sakuya_b6_build_clear_selected_building_effect = yes }",
      "cmp_regions2_clear_effect = { cmp_regions2_clear_building_selection_effect = yes remove_variable = cmp_regions2_mode_index remove_variable = cmp_regions2_operation_index remove_variable = cmp_regions2_amount_index remove_variable = cmp_regions2_preset_index cmp_regions2_clear_result_effect = yes }",
      "cmp_regions2_select_mode_building_effect = { set_variable = { name = cmp_regions2_mode_index value = 1 } remove_variable = cmp_regions2_preset_index cmp_regions2_clear_result_effect = yes }",
      "cmp_regions2_select_mode_resource_effect = { set_variable = { name = cmp_regions2_mode_index value = 2 } remove_variable = cmp_regions2_preset_index cmp_regions2_clear_result_effect = yes }",
      "cmp_regions2_select_mode_preset_effect = { cmp_regions2_clear_building_selection_effect = yes set_variable = { name = cmp_regions2_mode_index value = 3 } remove_variable = cmp_regions2_operation_index remove_variable = cmp_regions2_amount_index cmp_regions2_clear_result_effect = yes }",
    ]
    for b in buildings:
        L.append(f"cmp_regions2_select_building_{b['id']}_effect = {{ cmp_regions2_clear_building_selection_effect = yes set_variable = {b['selection_variable']} set_variable = {{ name = cmp_regions2_mode_index value = 1 }} remove_variable = cmp_regions2_preset_index cmp_regions2_clear_result_effect = yes }}")
        if b['id'] in cfg['resource_capable_buildings']:
            L.append(f"cmp_regions2_select_resource_{b['id']}_effect = {{ cmp_regions2_clear_building_selection_effect = yes set_variable = {b['selection_variable']} set_variable = {{ name = cmp_regions2_mode_index value = 2 }} remove_variable = cmp_regions2_preset_index cmp_regions2_clear_result_effect = yes }}")
    for i,name in enumerate(['add','set','remove'],1):
        extra=' remove_variable = cmp_regions2_amount_index' if name=='remove' else ''
        L.append(f"cmp_regions2_select_operation_{name}_effect = {{ set_variable = {{ name = cmp_regions2_operation_index value = {i} }}{extra} cmp_regions2_clear_result_effect = yes }}")
    for i,a in enumerate(amounts,1): L.append(f"cmp_regions2_select_amount_{a}_effect = {{ set_variable = {{ name = cmp_regions2_amount_index value = {i} }} cmp_regions2_clear_result_effect = yes }}")
    for i,p in enumerate(presets,1): L.append(f"cmp_regions2_select_preset_{p['id']}_effect = {{ set_variable = {{ name = cmp_regions2_preset_index value = {i} }} cmp_regions2_clear_result_effect = yes }}")
    L.append('')
    L.append(generate_add_one_exact_effect(maxlevel)); L.append('')
    L += [
      "cmp_regions2_build_add_one_guarded_effect = {",
      "  if = {",
      "    limit = {",
      "      NOT = { has_variable = cmp_regions2_state_blocked }",
      "      OR = {",
      "        AND = { NOT = { has_building = $BUILDING$ } can_construct_building = $BUILDING$ }",
      "        any_scope_building = { is_building_type = $BUILDING$ can_queue_building_levels = 1 }",
      "      }",
      "    }",
      "    cmp_regions2_build_add_one_exact_effect = { BUILDING = $BUILDING$ }",
      "  }",
      "  else_if = { limit = { NOT = { has_variable = cmp_regions2_state_blocked } } set_variable = cmp_regions2_state_blocked root = { set_variable = cmp_regions2_any_blocked } }",
      "}",
      ""
    ]
    for a in all_add_amounts: L.append(generate_add_effect(a)); L.append('')
    for a in amounts: L.append(generate_set_effect(a,maxlevel)); L.append('')
    L += ["cmp_regions2_apply_building_type_effect = {"]
    for i,a in enumerate(amounts,1):
        L.append(f"  if = {{ limit = {{ root.var:cmp_regions2_operation_index = 1 root.var:cmp_regions2_amount_index = {i} }} cmp_regions2_build_add_{a}_effect = {{ BUILDING = $BUILDING$ }} }}")
    for i,a in enumerate(amounts,1):
        L.append(f"  if = {{ limit = {{ root.var:cmp_regions2_operation_index = 2 root.var:cmp_regions2_amount_index = {i} }} cmp_regions2_build_set_{a}_effect = {{ BUILDING = $BUILDING$ }} }}")
    L += ["  if = { limit = { root.var:cmp_regions2_operation_index = 3 } remove_building = $BUILDING$ if = { limit = { state_has_building_type_levels = { target = bt:$BUILDING$ value = 0 } } root = { set_variable = cmp_regions2_any_success } } else = { root = { set_variable = cmp_regions2_any_failed } } }","}",""]
    for bt,r in res_by_bt.items():
        sid=r['id']; traits=[t['trait'] for t in r.get('tiers',[])]
        L += [f"cmp_regions2_resource_traits_clear_{sid}_effect = {{"]+remove_trait_lines(traits,'  ')+["}"]
        L += [f"cmp_regions2_resource_traits_set_{sid}_effect = {{",f"  cmp_regions2_resource_traits_clear_{sid}_effect = yes"]
        for i,a in enumerate(amounts,1):
            matching=[t['trait'] for t in r.get('tiers',[]) if t['value']==a]
            for trait in matching: L.append(f"  if = {{ limit = {{ root.var:cmp_regions2_amount_index = {i} }} state_region = {{ add_state_trait = {trait} }} }}")
        L += ["}",""]
    L += ["cmp_regions2_apply_resource_type_effect = {",
      "  if = { limit = { root.var:cmp_regions2_operation_index = 1 }",
      "    if = { limit = { NOT = { has_potential_resource = $BUILDING$ } } state_region = { add_resource_potential = $BUILDING$ }",
    ]
    for i,a in enumerate(amounts,1):
        if a>1: L.append(f"      if = {{ limit = {{ root.var:cmp_regions2_amount_index = {i} }} state_region = {{ change_resource_potential = {{ type = $BUILDING$ amount = {a-1} }} }} }}")
    L += ["    }","    else = {"]
    for i,a in enumerate(amounts,1): L.append(f"      if = {{ limit = {{ root.var:cmp_regions2_amount_index = {i} }} state_region = {{ change_resource_potential = {{ type = $BUILDING$ amount = {a} }} }} }}")
    L += ["    }","    if = { limit = { has_potential_resource = $BUILDING$ } root = { set_variable = cmp_regions2_any_success } } else = { root = { set_variable = cmp_regions2_any_failed } }","  }",
          "  if = { limit = { root.var:cmp_regions2_operation_index = 2 } if = { limit = { has_potential_resource = $BUILDING$ } state_region = { remove_resource_potential = $BUILDING$ } } state_region = { add_resource_potential = $BUILDING$ }"]
    for i,a in enumerate(amounts,1):
        if a>1: L.append(f"    if = {{ limit = {{ root.var:cmp_regions2_amount_index = {i} }} state_region = {{ change_resource_potential = {{ type = $BUILDING$ amount = {a-1} }} }} }}")
    L += ["    if = { limit = { has_potential_resource = $BUILDING$ } root = { set_variable = cmp_regions2_any_success } } else = { root = { set_variable = cmp_regions2_any_failed } }","  }",
          "  if = { limit = { root.var:cmp_regions2_operation_index = 3 } if = { limit = { has_potential_resource = $BUILDING$ } state_region = { remove_resource_potential = $BUILDING$ } } if = { limit = { NOT = { has_potential_resource = $BUILDING$ } } root = { set_variable = cmp_regions2_any_success } } else = { root = { set_variable = cmp_regions2_any_failed } } }","}",""]
    L += ["cmp_regions2_apply_selected_current_state_effect = {","  remove_variable = cmp_regions2_state_blocked"]
    for b in buildings:
        cond=selection_condition(b); bt=b['building_type']
        L += [f"  if = {{ limit = {{ root = {{ {cond} cmp_regions2_mode_building = yes }} }} cmp_regions2_apply_building_type_effect = {{ BUILDING = {bt} }} }}"]
        if bt in rb:
            L += [f"  if = {{ limit = {{ root = {{ {cond} cmp_regions2_mode_resource = yes }} }} cmp_regions2_apply_resource_type_effect = {{ BUILDING = {bt} }}"]
            if bt in res_by_bt:
                sid=res_by_bt[bt]['id']; L.append(f"    if = {{ limit = {{ root.var:cmp_regions2_operation_index = 2 }} cmp_regions2_resource_traits_set_{sid}_effect = yes }}"); L.append(f"    if = {{ limit = {{ root.var:cmp_regions2_operation_index = 3 }} cmp_regions2_resource_traits_clear_{sid}_effect = yes }}")
            L += ["  }"]
    for pi,p in enumerate(presets,1):
        L += [f"  if = {{ limit = {{ root = {{ cmp_regions2_mode_preset = yes var:cmp_regions2_preset_index = {pi} }} }}"]
        for bid,delta in p['buildings'].items():
            # A blocked/capped component must stop only that building, not the
            # remaining buildings in the preset. The root result flag keeps
            # the partial/blocked result visible after this local guard reset.
            L.append("    remove_variable = cmp_regions2_state_blocked")
            L.append(f"    cmp_regions2_build_add_{delta}_effect = {{ BUILDING = {b_by_id[bid]['building_type']} }}")
        L += ["  }"]
    L += ["  remove_variable = cmp_regions2_state_blocked","}",""]
    L += [
      "cmp_regions2_finish_result_effect = {",
      "  if = { limit = { has_variable = cmp_regions2_any_success OR = { has_variable = cmp_regions2_any_overflow has_variable = cmp_regions2_any_failed has_variable = cmp_regions2_any_blocked has_variable = cmp_regions2_any_unsafe } } set_variable = { name = cmp_regions2_result value = 3 } }",
      "  else_if = { limit = { has_variable = cmp_regions2_any_success } set_variable = { name = cmp_regions2_result value = 1 } }",
      "  else_if = { limit = { has_variable = cmp_regions2_any_unsafe } set_variable = { name = cmp_regions2_result value = 7 } }",
      "  else_if = { limit = { has_variable = cmp_regions2_any_blocked } set_variable = { name = cmp_regions2_result value = 6 } }",
      "  else_if = { limit = { has_variable = cmp_regions2_any_overflow } set_variable = { name = cmp_regions2_result value = 4 } }",
      "  else_if = { limit = { has_variable = cmp_regions2_any_failed } set_variable = { name = cmp_regions2_result value = 5 } }",
      "  else = { set_variable = { name = cmp_regions2_result value = 2 } }",
      "  remove_variable = cmp_regions2_any_success remove_variable = cmp_regions2_any_failed remove_variable = cmp_regions2_any_overflow remove_variable = cmp_regions2_any_blocked remove_variable = cmp_regions2_any_unsafe",
      "}",
      "cmp_regions2_apply_player_marked_effect = { cmp_regions2_clear_result_effect = yes every_scope_state = { limit = { has_decree = decree_sakuya_mark_state } cmp_regions2_apply_selected_current_state_effect = yes } cmp_regions2_finish_result_effect = yes }",
      "cmp_regions2_apply_incorporated_effect = { cmp_regions2_clear_result_effect = yes every_scope_state = { limit = { is_incorporated = yes } cmp_regions2_apply_selected_current_state_effect = yes } cmp_regions2_finish_result_effect = yes }",
      "cmp_regions2_apply_foreign_effect = { cmp_regions2_clear_result_effect = yes sakuya_b6_resolve_marked_country_effect = yes if = { limit = { exists = scope:sakuya_b6_marked_country_scope } scope:sakuya_b6_marked_country_scope = { every_scope_state = { limit = { has_variable = sakuya_mark_foreign_state_target } cmp_regions2_apply_selected_current_state_effect = yes } } } cmp_regions2_finish_result_effect = yes }",
      ""
    ]
    return '\n'.join(L)

def generate_staff_trigger(staffing,cfg):
    buildings=[b for b in staffing['buildings'] if b['status']=='SUPPORTED']
    new_any='OR = { ' + ' '.join(f"has_variable = {b['selection_variable']}" for b in buildings) + ' }'
    targets=cfg['staffing_occupancy_targets']
    def occupancy_branch(b, var):
        cond=' '.join(f"AND = {{ root.var:cmp_staffing_occupancy_target_index = {i+1} occupancy < {v/100:.2f} }}" for i,v in enumerate(targets))
        return f"AND = {{ root = {{ has_variable = {var} }} any_scope_building = {{ is_building_type = {b['building_type']} OR = {{ {cond} }} }} }}"
    L=[HEADER.rstrip(),'# Adaptive staffing: independent selector first, legacy B6 fallback second']
    L += ["cmp_staffing_occupancy_target_selected = { has_variable = cmp_staffing_occupancy_target_index }"]
    L += ["cmp_staffing_current_state_below_target = { OR = {"]
    L.append(f"  AND = {{ root = {{ {new_any} }} OR = {{")
    for b in buildings: L.append('    '+occupancy_branch(b,b['selection_variable']))
    L.append("  } }")
    legacy=[b for b in buildings if b.get('legacy_selection_variable')]
    if legacy:
        L.append(f"  AND = {{ root = {{ NOT = {{ {new_any} }} }} OR = {{")
        for b in legacy: L.append('    '+occupancy_branch(b,b['legacy_selection_variable']))
        L.append("  } }")
    L += ["} }",""]
    return '\n'.join(L)

def generate_staff_sgui(cfg):
    targets=cfg['staffing_occupancy_targets']; L=[HEADER.rstrip(),'# Adaptive staffing controls']
    L += ["cmp_staffing_adaptive_off_selected = { scope = country is_shown = { NOT = { has_variable = cmp_staffing_occupancy_target_index } } }","cmp_staffing_select_adaptive_off = { scope = country is_valid = { always = yes } effect = { cmp_staffing_select_adaptive_off_effect = yes } }"]
    for i,v in enumerate(targets,1):
        L.append(f"cmp_staffing_adaptive_{v}_selected = {{ scope = country is_shown = {{ var:cmp_staffing_occupancy_target_index = {i} }} }}")
        L.append(f"cmp_staffing_select_adaptive_{v} = {{ scope = country is_valid = {{ always = yes }} effect = {{ cmp_staffing_select_adaptive_{v}_effect = yes }} }}")
    L += [
      "cmp_staffing_result_applied = { scope = country is_shown = { var:cmp_staffing_result = 1 } }",
      "cmp_staffing_result_no_below_target = { scope = country is_shown = { var:cmp_staffing_result = 2 } }",
      ""
    ]
    return '\n'.join(L)

def generate_staff_effect(cfg):
    targets=cfg['staffing_occupancy_targets']; L=[HEADER.rstrip(),'# Adaptive staffing effects']
    L += ["cmp_staffing_clear_result_effect = { remove_variable = cmp_staffing_result }"]
    L += ["cmp_staffing_select_adaptive_off_effect = { remove_variable = cmp_staffing_occupancy_target_index cmp_staffing_clear_result_effect = yes }"]
    for i,v in enumerate(targets,1): L.append(f"cmp_staffing_select_adaptive_{v}_effect = {{ set_variable = {{ name = cmp_staffing_occupancy_target_index value = {i} }} cmp_staffing_clear_result_effect = yes }}")
    L += [
      "cmp_staffing_dispatch_current_state_effect = {",
      "  if = { limit = { root = { NOT = { has_variable = cmp_staffing_occupancy_target_index } } } cmp_staffing_apply_current_state_effect = yes root = { set_variable = { name = cmp_staffing_result value = 1 } } }",
      "  else_if = { limit = { cmp_staffing_current_state_below_target = yes } cmp_staffing_apply_current_state_effect = yes root = { set_variable = { name = cmp_staffing_result value = 1 } } }",
      "}",
      "cmp_staffing_dispatch_player_marked_effect = { cmp_staffing_clear_result_effect = yes every_scope_state = { limit = { has_decree = decree_sakuya_mark_state } cmp_staffing_dispatch_current_state_effect = yes } if = { limit = { NOT = { has_variable = cmp_staffing_result } } set_variable = { name = cmp_staffing_result value = 2 } } }",
      "cmp_staffing_dispatch_incorporated_effect = { cmp_staffing_clear_result_effect = yes every_scope_state = { limit = { is_incorporated = yes } cmp_staffing_dispatch_current_state_effect = yes } if = { limit = { NOT = { has_variable = cmp_staffing_result } } set_variable = { name = cmp_staffing_result value = 2 } } }",
      "cmp_staffing_dispatch_foreign_effect = { cmp_staffing_clear_result_effect = yes sakuya_b6_resolve_marked_country_effect = yes if = { limit = { exists = scope:sakuya_b6_marked_country_scope } scope:sakuya_b6_marked_country_scope = { every_scope_state = { limit = { has_variable = sakuya_mark_foreign_state_target } cmp_staffing_dispatch_current_state_effect = yes } } } if = { limit = { NOT = { has_variable = cmp_staffing_result } } set_variable = { name = cmp_staffing_result value = 2 } } }",
      ""
    ]
    return '\n'.join(L)

def button(loc, click, selected=None, enabled=None, width=82):
    enabled_attr = f' enabled = "{enabled}"' if enabled else ''
    if selected:
        return f'''widget = {{ size = {{ {width} 32 }}\n  button_standard = {{ size = {{ {width} 32 }} visible = "[Not(GetScriptedGui('{selected}').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End))]"{enabled_attr} onclick = "[GetScriptedGui('{click}').Execute(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" blockoverride "primary_visible" {{}} blockoverride "primary_texture" {{ texture = "gfx/interface/buttons/expand_button_bg_dropdown.dds" color = {{ 1 0.4 0.6 1 }} }} textbox = {{ size = {{ {width-6} 30 }} parentanchor = center autoresize = no maximumsize = {{ {width-6} 30 }} fontsize = 10 fontsize_min = 7 align = center|nobaseline text = "{loc}" }} }}\n  button_standard = {{ size = {{ {width} 32 }} visible = "[GetScriptedGui('{selected}').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" onclick = "[GetScriptedGui('{click}').Execute(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" blockoverride "primary_visible" {{}} blockoverride "primary_texture" {{ texture = "gfx/interface/buttons/expand_button_bg_dropdown.dds" color = {{ 0.45 0.9 0.5 1 }} }} textbox = {{ size = {{ {width-6} 30 }} parentanchor = center autoresize = no maximumsize = {{ {width-6} 30 }} fontsize = 10 fontsize_min = 7 align = center|nobaseline text = "{loc}" }} }}\n}}'''
    return f'''button_standard = {{ size = {{ {width} 32 }}{enabled_attr} onclick = "[GetScriptedGui('{click}').Execute(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" blockoverride "primary_visible" {{}} blockoverride "primary_texture" {{ texture = "gfx/interface/buttons/expand_button_bg_dropdown.dds" color = {{ 1 0.4 0.6 1 }} }} textbox = {{ size = {{ {width-6} 30 }} parentanchor = center autoresize = no maximumsize = {{ {width-6} 30 }} fontsize = 10 fontsize_min = 7 align = center|nobaseline text = "{loc}" }} }}'''

def generate_gui_block(cfg):
    amounts=cfg['building_amounts']; presets=cfg['presets']
    L=[BEGIN]
    # submode bar
    L += ['''widget = {
  visible = "[And(GetVariableSystem.Exists('sakuya_test_btn6_clicked'), GetVariableSystem.HasValue('sakuya_btn6_tab', 'staffing'))]"
  position = { 0 230 } size = { 742 34 }
  widget = { position = { 160 0 } size = { 552 34 } hbox = { spacing = 8''']
    # direct VariableSystem for submode
    L += ['''    widget = { size = { 180 32 }
      button_standard = { size = { 180 32 } visible = "[GetVariableSystem.HasValue('cmp_b6_assistant_mode', 'operations')]" onclick = "[GetVariableSystem.Clear('cmp_b6_assistant_mode')]" blockoverride "primary_visible" {} blockoverride "primary_texture" { texture = "gfx/interface/buttons/expand_button_bg_dropdown.dds" color = { 1 0.4 0.6 1 } } textbox = { size = { 174 30 } parentanchor = center autoresize = no maximumsize = { 174 30 } fontsize = 11 fontsize_min = 8 align = center|nobaseline text = "CMP_RB2_SUBMODE_STAFF" } }
      button_standard = { size = { 180 32 } visible = "[Not(GetVariableSystem.HasValue('cmp_b6_assistant_mode', 'operations'))]" onclick = "[GetVariableSystem.Clear('cmp_b6_assistant_mode')]" blockoverride "primary_visible" {} blockoverride "primary_texture" { texture = "gfx/interface/buttons/expand_button_bg_dropdown.dds" color = { 0.45 0.9 0.5 1 } } textbox = { size = { 174 30 } parentanchor = center autoresize = no maximumsize = { 174 30 } fontsize = 11 fontsize_min = 8 align = center|nobaseline text = "CMP_RB2_SUBMODE_STAFF" } }
    }''']
    L += ['''    widget = { size = { 180 32 }
      button_standard = { size = { 180 32 } visible = "[Not(GetVariableSystem.HasValue('cmp_b6_assistant_mode', 'operations'))]" onclick = "[GetVariableSystem.Set('cmp_b6_assistant_mode', 'operations')]" blockoverride "primary_visible" {} blockoverride "primary_texture" { texture = "gfx/interface/buttons/expand_button_bg_dropdown.dds" color = { 1 0.4 0.6 1 } } textbox = { size = { 174 30 } parentanchor = center autoresize = no maximumsize = { 174 30 } fontsize = 11 fontsize_min = 8 align = center|nobaseline text = "CMP_RB2_SUBMODE_OPERATIONS" } }
      button_standard = { size = { 180 32 } visible = "[GetVariableSystem.HasValue('cmp_b6_assistant_mode', 'operations')]" onclick = "[GetVariableSystem.Set('cmp_b6_assistant_mode', 'operations')]" blockoverride "primary_visible" {} blockoverride "primary_texture" { texture = "gfx/interface/buttons/expand_button_bg_dropdown.dds" color = { 0.45 0.9 0.5 1 } } textbox = { size = { 174 30 } parentanchor = center autoresize = no maximumsize = { 174 30 } fontsize = 11 fontsize_min = 8 align = center|nobaseline text = "CMP_RB2_SUBMODE_OPERATIONS" } }
    }''']
    L += ['''  } }
}''']
    # operations panel
    L += ['''widget = {
  visible = "[And(And(GetVariableSystem.Exists('sakuya_test_btn6_clicked'), GetVariableSystem.HasValue('sakuya_btn6_tab', 'staffing')), GetVariableSystem.HasValue('cmp_b6_assistant_mode', 'operations'))]"
  position = { 0 268 } size = { 742 292 }
  widget = { position = { 160 0 } size = { 552 24 } textbox = { size = { 552 24 } maximumsize = { 552 24 } fontsize = 17 fontsize_min = 10 align = left|nobaseline text = "CMP_RB2_HEADER" } }
  widget = { position = { 160 27 } size = { 552 32 } hbox = { spacing = 6''']
    L += [button('CMP_RB2_MODE_BUILDING','cmp_regions2_select_mode_building','cmp_regions2_mode_building_selected',width=150),button('CMP_RB2_MODE_RESOURCE','cmp_regions2_select_mode_resource','cmp_regions2_mode_resource_selected',"[GetScriptedGui('cmp_regions2_select_mode_resource').IsValid(GuiScope.SetRoot(GetPlayer.MakeScope).End)]",150),button('CMP_RB2_MODE_PRESET','cmp_regions2_select_mode_preset','cmp_regions2_mode_preset_selected',width=150)]
    L += ['''  } }
  widget = { visible = "[Not(GetScriptedGui('cmp_regions2_mode_preset_selected').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End))]" position = { 160 64 } size = { 552 32 } hbox = { spacing = 8''']
    L += [button('CMP_RB2_OP_ADD','cmp_regions2_select_operation_add','cmp_regions2_operation_add_selected',width=170),button('CMP_RB2_OP_SET','cmp_regions2_select_operation_set','cmp_regions2_operation_set_selected',width=170),button('CMP_RB2_OP_REMOVE_CLEAR','cmp_regions2_select_operation_remove','cmp_regions2_operation_remove_selected',width=170)]
    L += ['''  } }
  widget = { visible = "[Not(GetScriptedGui('cmp_regions2_mode_preset_selected').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End))]" position = { 160 101 } size = { 552 32 } hbox = { spacing = 5''']
    for a in amounts: L.append(button(f'CMP_RB2_AMOUNT_{a}',f'cmp_regions2_select_amount_{a}',f'cmp_regions2_amount_{a}_selected',width=84))
    L += ['''  } }
  widget = { visible = "[GetScriptedGui('cmp_regions2_mode_preset_selected').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" position = { 160 64 } size = { 552 69 } vbox = { spacing = 5''']
    # preset buttons two rows
    L += ['''    widget = { size = { 552 32 } hbox = { spacing = 6''']
    for p in presets[:2]: L.append(button(f"CMP_RB2_PRESET_{p['id'].upper()}",f"cmp_regions2_select_preset_{p['id']}",f"cmp_regions2_preset_{p['id']}_selected",width=260))
    L += ['''    } }
    widget = { size = { 552 32 } hbox = { spacing = 6''']
    for p in presets[2:]: L.append(button(f"CMP_RB2_PRESET_{p['id'].upper()}",f"cmp_regions2_select_preset_{p['id']}",f"cmp_regions2_preset_{p['id']}_selected",width=260))
    L += ['''    } }
  } }
  widget = { position = { 160 139 } size = { 552 36 } hbox = { spacing = 8''']
    L += [button('CMP_RB2_TARGET_MARKED','cmp_regions2_apply_player_marked',enabled="[GetScriptedGui('cmp_regions2_can_player_marked').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]",width=175),button('CMP_RB2_TARGET_INCORPORATED','cmp_regions2_apply_incorporated',enabled="[GetScriptedGui('cmp_regions2_can_incorporated').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]",width=175),button('CMP_RB2_TARGET_FOREIGN','cmp_regions2_apply_foreign',enabled="[GetScriptedGui('cmp_regions2_can_foreign').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]",width=175)]
    L += ['''  } }
  widget = { position = { 160 181 } size = { 552 48 }
    textbox = { visible = "[GetScriptedGui('cmp_regions2_result_success').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" size = { 552 20 } fontsize = 11 align = left|nobaseline text = "CMP_RB2_RESULT_SUCCESS" }
    textbox = { visible = "[GetScriptedGui('cmp_regions2_result_no_target').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" size = { 552 20 } fontsize = 11 align = left|nobaseline text = "CMP_RB2_RESULT_NO_TARGET" }
    textbox = { visible = "[GetScriptedGui('cmp_regions2_result_partial').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" size = { 552 20 } fontsize = 11 align = left|nobaseline text = "CMP_RB2_RESULT_PARTIAL" }
    textbox = { visible = "[GetScriptedGui('cmp_regions2_result_add_limit').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" size = { 552 20 } fontsize = 11 align = left|nobaseline text = "CMP_RB2_RESULT_ADD_LIMIT" }
    textbox = { visible = "[GetScriptedGui('cmp_regions2_result_failed').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" size = { 552 20 } fontsize = 11 align = left|nobaseline text = "CMP_RB2_RESULT_FAILED" }
    textbox = { visible = "[GetScriptedGui('cmp_regions2_result_blocked').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" size = { 552 20 } fontsize = 11 align = left|nobaseline text = "CMP_RB2_RESULT_BLOCKED" }
    textbox = { visible = "[GetScriptedGui('cmp_regions2_result_unsafe').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" size = { 552 20 } fontsize = 11 align = left|nobaseline text = "CMP_RB2_RESULT_UNSAFE" }
    textbox = { position = { 0 22 } size = { 552 26 } maximumsize = { 552 26 } fontsize = 9 fontsize_min = 7 multiline = yes align = left|nobaseline text = "CMP_RB2_HINT" }
  }
  button_standard = { position = { 620 181 } size = { 80 28 } onclick = "[GetScriptedGui('cmp_regions2_clear').Execute(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" blockoverride "primary_visible" {} blockoverride "primary_texture" { texture = "gfx/interface/buttons/expand_button_bg_dropdown.dds" color = { 0.4 0.4 0.45 1 } } textbox = { size = { 74 26 } parentanchor = center fontsize = 9 align = center|nobaseline text = "CMP_RB2_CLEAR" } }
}''']
    L.append(END)
    return '\n'.join(L)

def find_widget(gui, needle):
    pos=gui.find(needle)
    if pos<0: raise RuntimeError(f'needle not found: {needle}')
    start=gui.rfind('widget = {',0,pos)
    if start<0: raise RuntimeError('widget start not found')
    brace=gui.find('{',start); depth=0
    for i in range(brace,len(gui)):
        if gui[i]=='{': depth+=1
        elif gui[i]=='}':
            depth-=1
            if depth==0: return start,i+1
    raise RuntimeError('unclosed widget')

def patch_gui(gui, block, cfg):
    # remove existing generated block
    if BEGIN in gui and END in gui:
        gui=re.sub(r'(?ms)^[ \t]*'+re.escape(BEGIN)+r'.*?^[ \t]*'+re.escape(END)+r'[ \t]*\n?', '', gui, count=1)
    if ADAPT_BEGIN in gui and ADAPT_END in gui:
        gui=re.sub(r'(?ms)^[ \t]*'+re.escape(ADAPT_BEGIN)+r'.*?^[ \t]*'+re.escape(ADAPT_END)+r'[ \t]*\n?', '', gui, count=1)
    needle='visible = "[And(GetVariableSystem.Exists(\'sakuya_test_btn6_clicked\'), GetVariableSystem.HasValue(\'sakuya_btn6_tab\', \'staffing\'))]"'
    patched_needle='visible = "[And(And(GetVariableSystem.Exists(\'sakuya_test_btn6_clicked\'), GetVariableSystem.HasValue(\'sakuya_btn6_tab\', \'staffing\')), Not(GetVariableSystem.HasValue(\'cmp_b6_assistant_mode\', \'operations\')))]"'
    active_needle = needle if needle in gui else patched_needle
    s,e=find_widget(gui,active_needle)
    line_start=gui.rfind('\n',0,s)+1
    indent=gui[line_start:s]
    s=line_start
    old=gui[s:e]
    # Normalize an already generated panel before rebuilding it.
    old=old.replace("position = { 0 268 }","position = { 0 230 }",1)
    old=old.replace('size = { 742 270 }','size = { 742 186 }',1)
    old=old.replace(patched_needle, needle, 1)
    # shift legacy staffing content and hide in operations submode
    old=old.replace("position = { 0 230 }","position = { 0 268 }",1)
    old=old.replace(needle, patched_needle,1)
    # add adaptive controls to legacy panel before its closing brace
    adaptive='''\n                        # CMP_STAFF_ADAPTIVE_BEGIN generated_controls\n                        widget = { position = { 160 187 } size = { 552 32 } hbox = { spacing = 5\n                            textbox = { size = { 132 30 } maximumsize = { 132 30 } fontsize = 9 fontsize_min = 7 align = left|nobaseline text = "CMP_STAFF_ADAPTIVE_LABEL" }\n'''
    adaptive += button('CMP_STAFF_ADAPTIVE_OFF','cmp_staffing_select_adaptive_off','cmp_staffing_adaptive_off_selected',width=72)+'\n'
    for v in cfg['staffing_occupancy_targets']:
        adaptive += button(f'CMP_STAFF_ADAPTIVE_{v}',f'cmp_staffing_select_adaptive_{v}',f'cmp_staffing_adaptive_{v}_selected',width=72)+'\n'
    adaptive += '''                        } }\n                        widget = { position = { 160 222 } size = { 552 40 }\n                            textbox = { visible = "[GetScriptedGui('cmp_staffing_result_applied').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" size = { 552 18 } fontsize = 9 align = left|nobaseline text = "CMP_STAFF_RESULT_APPLIED" }\n                            textbox = { visible = "[GetScriptedGui('cmp_staffing_result_no_below_target').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" size = { 552 18 } fontsize = 9 align = left|nobaseline text = "CMP_STAFF_RESULT_NO_BELOW" }\n                            textbox = { position = { 0 18 } size = { 552 22 } maximumsize = { 552 22 } fontsize = 8 fontsize_min = 6 multiline = yes align = left|nobaseline text = "CMP_STAFF_ADAPTIVE_HINT" }\n                        }\n                        # CMP_STAFF_ADAPTIVE_END generated_controls\n'''
    # increase size and insert before final closing brace
    old=old.replace('size = { 742 186 }','size = { 742 270 }',1)
    old=old.rstrip()
    old=old[:-1].rstrip()+'\n'+adaptive+old[-1:]
    indented_block='\n'.join((indent+line if line else line) for line in block.splitlines())
    gui=gui[:s]+indented_block+'\n'+old+gui[e:]
    # The legacy selected-building card at y=470 overlaps the expanded Staffing panel.
    gui=gui.replace('        visible = "[And(GetVariableSystem.Exists(\'sakuya_test_btn6_clicked\'), Or(Or(GetVariableSystem.HasValue(\'sakuya_btn6_tab\', \'building\'), GetVariableSystem.HasValue(\'sakuya_btn6_tab\', \'reserved\')), GetVariableSystem.HasValue(\'sakuya_btn6_tab\', \'staffing\')))]"', '        visible = "[And(GetVariableSystem.Exists(\'sakuya_test_btn6_clicked\'), Or(GetVariableSystem.HasValue(\'sakuya_btn6_tab\', \'building\'), GetVariableSystem.HasValue(\'sakuya_btn6_tab\', \'reserved\')))]"', 1)
    return gui

def patch_staffing_sgui(pathtext):
    # redirect existing apply endpoints to adaptive dispatcher while preserving validity checks
    replacements={
      'effect = { cmp_staffing_apply_player_marked_states_effect = yes }':'effect = { cmp_staffing_dispatch_player_marked_effect = yes }',
      'effect = { cmp_staffing_apply_player_incorporated_states_effect = yes }':'effect = { cmp_staffing_dispatch_incorporated_effect = yes }',
      'effect = { cmp_staffing_apply_marked_country_states_effect = yes }':'effect = { cmp_staffing_dispatch_foreign_effect = yes }',
    }
    for a,b in replacements.items(): pathtext=pathtext.replace(a,b)
    return pathtext

def patch_legacy_build_effects(text):
    old="""sakuya_b6_build_select_building_effect = {
	sakuya_b6_build_clear_selected_building_effect = yes
	set_variable = $VAR$
}"""
    new="""sakuya_b6_build_select_building_effect = {
	cmp_regions2_clear_new_building_selection_effect = yes
	sakuya_b6_build_clear_selected_building_effect = yes
	set_variable = $VAR$
}"""
    if old in text: return text.replace(old,new,1)
    if new in text: return text
    raise RuntimeError('legacy building selection effect anchor not found')

def outputs():
    buildings=load('buildings.json')['buildings']; resources=load('resources.json')['resources']; cfg=load('regions_buildings.json'); staffing=load('staffing.json')
    b_ids={b['id'] for b in buildings}; errors=[]
    if len(b_ids)!=len(buildings): errors.append('duplicate building id')
    vars_=[b['selection_variable'] for b in buildings]
    if len(vars_)!=len(set(vars_)): errors.append('duplicate Regions operation selection variable')
    if any(not v.startswith('cmp_regions2_sel_') for v in vars_): errors.append('Regions operation selector is not independent cmp_regions2_sel_*')
    for x in cfg['resource_capable_buildings']:
        if x not in b_ids: errors.append('unknown resource building '+x)
    for p in cfg['presets']:
        for x in p['buildings']:
            if x not in b_ids: errors.append(f"preset {p['id']} unknown building {x}")
    if errors: raise RuntimeError('\n'.join(errors))
    block=generate_gui_block(cfg)
    gui=GUI.read_text(encoding='utf-8-sig'); patched=patch_gui(gui,block,cfg)
    staff_sgui_path=ROOT/'common/scripted_guis/cmp_staffing_sgui.txt'; staff_sgui=patch_staffing_sgui(staff_sgui_path.read_text(encoding='utf-8-sig'))
    legacy_effect_path=ROOT/'common/scripted_effects/sakuya_cheat_b6_effects.txt'; legacy_effect=patch_legacy_build_effects(legacy_effect_path.read_text(encoding='utf-8-sig'))
    all_add_amounts=sorted(set(cfg['building_amounts']) | {delta for p in cfg['presets'] for delta in p['buildings'].values()})
    out={
      TRIGGER:generate_triggers(buildings,resources,cfg),
      SGUI:generate_regions_sgui(buildings,cfg),
      EFFECT:generate_regions_effects(buildings,resources,cfg),
      STAFF_TRIGGER:generate_staff_trigger(staffing,cfg),
      STAFF_SGUI:generate_staff_sgui(cfg),
      STAFF_EFFECT:generate_staff_effect(cfg),
      GUI:patched,
      staff_sgui_path:staff_sgui,
      legacy_effect_path:legacy_effect,
      GENERATED/'regions2_panel.gui.txt':block+'\n',
    }
    manifest={'schema_version':2,'counts':{'buildings':len(buildings),'resource_capable':len(cfg['resource_capable_buildings']),'presets':len(cfg['presets']),'amounts':len(cfg['building_amounts']),'generated_add_amounts':len(all_add_amounts),'adaptive_targets':len(cfg['staffing_occupancy_targets']),'staffing_supported':sum(1 for b in staffing['buildings'] if b['status']=='SUPPORTED')},'add_amounts_generated':all_add_amounts,'add_exact_max_existing_level':cfg['add_exact_max_existing_level'],'operation_contract':cfg.get('building_operation_contract',{}),'generated':{str(p.relative_to(ROOT)):sha(t) for p,t in out.items() if p!=GUI}}
    out[GENERATED/'regions2_manifest.json']=json.dumps(manifest,indent=2,ensure_ascii=False)+'\n'
    return out,manifest

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); args=ap.parse_args()
    out,manifest=outputs()
    if args.check:
        stale=[]
        for p,t in out.items():
            if not p.exists(): stale.append('missing '+str(p.relative_to(ROOT))); continue
            enc='utf-8-sig' if p.suffix in {'.txt','.gui'} or p.name=='sakuya_main.gui' else 'utf-8'
            if p.read_text(encoding=enc)!=t: stale.append('stale '+str(p.relative_to(ROOT)))
        if stale:
            print('REGIONS2_CHECK_FAIL'); print('\n'.join(stale)); return 1
        print('REGIONS2_CHECK_PASS',json.dumps(manifest['counts'],sort_keys=True)); return 0
    for p,t in out.items():
        if p.suffix in {'.txt','.gui'} or p.name=='sakuya_main.gui': wbom(p,t)
        else: wplain(p,t)
    print('REGIONS2_GENERATE_PASS',json.dumps(manifest['counts'],sort_keys=True)); return 0
if __name__=='__main__': sys.exit(main())
