#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
REG=ROOT/'registry/navy18.json'; CAT=ROOT/'registry/naval_catalog.json'
SGUI=ROOT/'common/scripted_guis/cmp_navy18_composition_sgui.txt'
EFFECT=ROOT/'common/scripted_effects/cmp_navy18_composition_effects.txt'
LOC_RU=ROOT/'localization/russian/cmp_navy18_l_russian.yml'; LOC_EN=ROOT/'localization/english/cmp_navy18_l_english.yml'
HEADER='# AUTO-GENERATED by tools/generate_navy18.py. DO NOT EDIT BY HAND.\n'

def load(): return json.loads(REG.read_text(encoding='utf-8')), json.loads(CAT.read_text(encoding='utf-8'))
def provider_gate(h): return 'always = yes' if h.get('provider')=='vanilla' else ('cmp_provider_tech_res_active = yes' if h.get('provider')=='tech_res' else 'always = no')
def tech_gate(h): return 'always = yes' if not h.get('unlock_technology') else f"has_technology_researched = {h['unlock_technology']}"
def hvar(r): return f'cmp_navy18_comp2_row_{r}_hull_index'
def cvar(r): return f'cmp_navy18_comp2_row_{r}_count'
def selected_hull_cond(r,idx): return f'var:{hvar(r)} = {idx}'
def count_cond(r,a): return f'NOT = {{ has_variable = {cvar(r)} }}' if a==0 else f'var:{cvar(r)} = {a}'

def row_valid_clause(r,hulls):
    ors=[f'NOT = {{ has_variable = {cvar(r)} }}']
    for idx,h in enumerate(hulls,1):
        ors.append(f'AND = {{ {selected_hull_cond(r,idx)} {provider_gate(h)} {tech_gate(h)} }}')
    return 'OR = { '+' '.join(ors)+' }'

def has_any_clause(rows): return 'OR = { '+' '.join(f'has_variable = {cvar(r)}' for r in rows)+' }'

def generate_sgui(cfg,cat):
    hulls=cat['combat_hulls']; rows=list(range(1,cfg['composer2']['rows']+1)); amounts=cfg['composer2']['amounts']
    lines=[HEADER.rstrip(),'# beta18-pre3 Fleet Composer 2.0: five arbitrary hull rows over the full combat catalog.']
    for h in hulls:
        hid=h['id']; lines.append(f'cmp_navy18_comp2_hull_{hid}_available = {{ scope = country is_shown = {{ {provider_gate(h)} {tech_gate(h)} }} }}')
    for r in rows:
        for idx,h in enumerate(hulls,1):
            hid=h['id']
            lines.append(f'cmp_navy18_comp2_row_{r}_hull_{hid}_selected = {{ scope = country is_shown = {{ {selected_hull_cond(r,idx)} }} }}')
            lines.append(f'cmp_navy18_comp2_select_row_{r}_hull_{hid} = {{ scope = country is_valid = {{ {provider_gate(h)} {tech_gate(h)} }} effect = {{ cmp_navy18_comp2_select_row_{r}_hull_{hid}_effect = yes }} }}')
        has_hull='OR = { '+' '.join(selected_hull_cond(r,idx) for idx,_ in enumerate(hulls,1))+' }'
        lines.append(f'cmp_navy18_comp2_row_{r}_has_hull = {{ scope = country is_shown = {{ {has_hull} }} }}')
        for a in amounts:
            lines.append(f'cmp_navy18_comp2_row_{r}_count_{a}_selected = {{ scope = country is_shown = {{ {count_cond(r,a)} }} }}')
            lines.append(f'cmp_navy18_comp2_select_row_{r}_count_{a} = {{ scope = country is_valid = {{ always = yes }} effect = {{ cmp_navy18_comp2_select_row_{r}_count_{a}_effect = yes }} }}')
        lines.append(f'cmp_navy18_comp2_row_{r}_ready = {{ scope = country is_shown = {{ {row_valid_clause(r,hulls)} }} }}')
    lines += [
      'cmp_navy18_has_marked_port_state = { scope = country is_shown = { any_scope_state = { has_decree = decree_sakuya_mark_state owner = root has_port_state = yes } } }',
      f'cmp_navy18_comp2_has_any_ship = {{ scope = country is_shown = {{ {has_any_clause(rows)} }} }}',
      'cmp_navy18_comp2_ready = { scope = country is_shown = { any_scope_state = { has_decree = decree_sakuya_mark_state owner = root has_port_state = yes } '+has_any_clause(rows)
    ]
    for r in rows: lines.append('    '+row_valid_clause(r,hulls))
    lines += ['} }','cmp_navy18_comp2_create_fleet = { scope = country is_valid = { any_scope_state = { has_decree = decree_sakuya_mark_state owner = root has_port_state = yes } '+has_any_clause(rows)]
    for r in rows: lines.append('    '+row_valid_clause(r,hulls))
    lines += ['} effect = { cmp_navy18_comp2_create_fleet_effect = yes } }','cmp_navy18_comp2_clear = { scope = country is_valid = { always = yes } effect = { cmp_navy18_comp2_clear_effect = yes } }']
    for p in cfg['presets']:
        lines.append(f"cmp_navy18_preset_{p['id']} = {{ scope = country is_valid = {{ always = yes }} effect = {{ cmp_navy18_preset_{p['id']}_effect = yes }} }}")
    lines += [
      'cmp_navy18_result_created = { scope = country is_shown = { var:cmp_navy18_result = 1 } }',
      'cmp_navy18_result_failed = { scope = country is_shown = { var:cmp_navy18_result = 2 } }',
      'cmp_navy18_result_preset = { scope = country is_shown = { var:cmp_navy18_result = 3 } }',''
    ]
    return '\n'.join(lines)

def create_ship_lines(ship_type,count,indent='            '):
    return [f'{indent}create_ship = {{ type = ship_type:{ship_type} fleet = scope:cmp_navy18_comp2_new_fleet }}' for _ in range(count)]

def set_best_hull(lines,row,candidates,hulls,indent='    '):
    idx={h['id']:i for i,h in enumerate(hulls,1)}; by={h['id']:h for h in hulls}
    for hid in candidates:
        if hid not in by: continue
        h=by[hid]
        lines.append(f'{indent}if = {{ limit = {{ {provider_gate(h)} {tech_gate(h)} }} set_variable = {{ name = {hvar(row)} value = {idx[hid]} }} }}')

def group_ids(hulls,group): return [h['id'] for h in hulls if h['group']==group]

def generate_effects(cfg,cat):
    hulls=cat['combat_hulls']; rows=list(range(1,cfg['composer2']['rows']+1)); amounts=cfg['composer2']['amounts']; nonzero=[a for a in amounts if a]
    lines=[HEADER.rstrip(),'# beta18-pre3 Fleet Composer 2.0.','## Creation strategy: first non-zero row is the anchor create_military_formation.','## create_military_formation save_temporary_scope_as captures the exact new fleet; remaining rows use create_ship against it.']
    lines.append('cmp_navy18_clear_result_effect = { remove_variable = cmp_navy18_result }')
    lines.append('cmp_navy18_comp2_clear_effect = {')
    for r in rows: lines += [f'    remove_variable = {hvar(r)}',f'    remove_variable = {cvar(r)}']
    lines += ['    remove_variable = cmp_navy18_comp2_anchor_row','    remove_variable = cmp_navy18_result','}']
    for r in rows:
        for idx,h in enumerate(hulls,1):
            lines.append(f"cmp_navy18_comp2_select_row_{r}_hull_{h['id']}_effect = {{ set_variable = {{ name = {hvar(r)} value = {idx} }} cmp_navy18_clear_result_effect = yes }}")
        for a in amounts:
            body=f'remove_variable = {cvar(r)}' if a==0 else f'set_variable = {{ name = {cvar(r)} value = {a} }}'
            lines.append(f'cmp_navy18_comp2_select_row_{r}_count_{a}_effect = {{ {body} cmp_navy18_clear_result_effect = yes }}')
    # Era-aware presets fill rows only; creation remains separate.
    capital=group_ids(hulls,'capital'); cruiser=group_ids(hulls,'cruiser'); torpedo=group_ids(hulls,'torpedo')
    carriers=[x for x in ['seaplane_tender','aircraft_carrier','nuclear_carrier'] if x in {h['id'] for h in hulls}]
    subs=[x for x in ['submarine','nuclear_submarine'] if x in {h['id'] for h in hulls}]
    troop=[x for x in ['frigate','iron_frigate','troop_ship'] if x in {h['id'] for h in hulls}]
    preset_rows={
      'escort':[(1,cruiser,3),(2,torpedo,5)],
      'battle':[(1,capital,3),(2,cruiser,5),(3,torpedo,5)],
      'carrier':[(1,carriers,1),(2,capital,3),(3,torpedo,5)],
      'wolfpack':[(1,subs,10)],
      'amphibious':[(1,troop,5),(2,capital,1),(3,torpedo,3)],
    }
    for p in cfg['presets']:
        pid=p['id']; lines.append(f'cmp_navy18_preset_{pid}_effect = {{ cmp_navy18_comp2_clear_effect = yes')
        for row,candidates,count in preset_rows[pid]:
            lines.append(f'    set_variable = {{ name = {cvar(row)} value = {count} }}')
            set_best_hull(lines,row,candidates,hulls,'    ')
        lines += ['    set_variable = { name = cmp_navy18_result value = 3 }','}']
    lines += [
      'cmp_navy18_resolve_hq_effect = {',
      '    clear_saved_scope = cmp_navy18_spawn_state',
      '    clear_saved_scope = cmp_navy18_hq_region',
      '    ordered_scope_state = { limit = { has_decree = decree_sakuya_mark_state owner = root has_port_state = yes } order_by = gdp position = 0 check_range_bounds = no save_scope_as = cmp_navy18_spawn_state }',
      '    if = { limit = { exists = scope:cmp_navy18_spawn_state } scope:cmp_navy18_spawn_state = { region = { save_scope_as = cmp_navy18_hq_region } } }',
      '}',
      'cmp_navy18_comp2_create_fleet_effect = {',
      '    remove_variable = cmp_navy18_result',
      '    remove_variable = cmp_navy18_comp2_anchor_row',
      '    cmp_navy18_resolve_hq_effect = yes',
      '    if = {',
      '        limit = { exists = scope:cmp_navy18_hq_region '+has_any_clause(rows)
    ]
    for r in rows: lines.append('            '+row_valid_clause(r,hulls))
    lines += ['        }']
    # First non-zero row anchors the fleet. 500 bounded anchor branches max.
    for r in rows:
        for idx,h in enumerate(hulls,1):
            for a in nonzero:
                lines += [
                  '        if = {',
                  f'            limit = {{ NOT = {{ has_variable = cmp_navy18_comp2_anchor_row }} {selected_hull_cond(r,idx)} {count_cond(r,a)} {provider_gate(h)} {tech_gate(h)} }}',
                  '            create_military_formation = {',
                  '                type = fleet',
                  '                hq_region = scope:cmp_navy18_hq_region',
                  f"                ship = {{ type = ship_type:{h['ship_type']} count = {a} }}",
                  '                save_temporary_scope_as = cmp_navy18_comp2_new_fleet',
                  '            }',
                  f'            set_variable = {{ name = cmp_navy18_comp2_anchor_row value = {r} }}',
                  '        }'
                ]
    # Add every non-anchor row directly to the exact newly-created fleet.
    lines += ['        if = {','            limit = { exists = scope:cmp_navy18_comp2_new_fleet }']
    for r in rows:
        for idx,h in enumerate(hulls,1):
            for a in nonzero:
                lines += [
                  '            if = {',
                  f'                limit = {{ NOT = {{ var:cmp_navy18_comp2_anchor_row = {r} }} {selected_hull_cond(r,idx)} {count_cond(r,a)} {provider_gate(h)} {tech_gate(h)} }}'
                ]
                lines += create_ship_lines(h['ship_type'],a,'                ')
                lines += ['            }']
    lines += [
      '            set_variable = { name = cmp_navy18_result value = 1 }',
      '        }',
      '    }',
      '    if = { limit = { NOT = { var:cmp_navy18_result = 1 } } set_variable = { name = cmp_navy18_result value = 2 } }',
      '    remove_variable = cmp_navy18_comp2_anchor_row',
      '}',
      ''
    ]
    return '\n'.join(lines)

def generate_loc(cfg,cat,lang):
    ru=lang=='russian'; L=['l_russian:' if ru else 'l_english:']; add=lambda k,v:L.append(f' {k}:0 "{v}"')
    if ru:
      vals={
      'CMP_NAVY18_MODE_NEW':'КОНСТРУКТОР ФЛОТА 2.0','CMP_NAVY18_MODE_EXISTING':'ФЛОТ',
      'CMP_NAVY18_PORT_OPEN':'Выбрать портовую область','CMP_NAVY18_PORT_READY':'#P Портовая область выбрана#!','CMP_NAVY18_PORT_NONE':'#N Отметьте собственную область с портом#!','CMP_NAVY18_PORT_TT':'Новый флот создаётся отдельно в отмеченной собственной портовой области; при нескольких используется область с наибольшим ВВП.',
      'CMP_NAVY18_NEW_TITLE':'Конструктор флота 2.0','CMP_NAVY18_NEW_DESC':'Пять независимых строк. В каждой выберите любой доступный корпус из полного каталога и количество 0/1/3/5/10. Все ненулевые строки собираются в один новый флот.',
      'CMP_NAVY18_COMP2_ROW':'Строка состава','CMP_NAVY18_COMP2_SELECT_HULL':'Выбрать / изменить корпус','CMP_NAVY18_COMP2_NO_HULL':'Корпус не выбран','CMP_NAVY18_COMP2_BACK':'Вернуться к составу','CMP_NAVY18_COMP2_PICK_TITLE':'Выбор корпуса для строки','CMP_NAVY18_COMP2_PICK_DESC':'Доступны все 25 боевых корпусов. Закрытые технологиями варианты видны, но недоступны. Повтор одного корпуса в нескольких строках разрешён — количества суммируются.',
      'CMP_NAVY18_COMP2_READY':'#P Состав готов к созданию#!','CMP_NAVY18_COMP2_BAD':'#N Проверьте: порт, ненулевые строки, выбранные корпуса и технологии#!','CMP_NAVY18_COMP2_DUPLICATES':'Повтор корпуса в разных строках допустим: итоговое количество складывается.',
      'CMP_NAVY18_COMPOSITION':'Состав нового флота','CMP_NAVY18_CREATE':'СОЗДАТЬ ОДИН ФЛОТ','CMP_NAVY18_CREATE_TT':'Первая ненулевая строка создаёт новый флот; остальные строки добавляются в этот же точный флот внутри одной операции. Мгновенное создание использует штатный шаблон типа по умолчанию.',
      'CMP_NAVY18_CLEAR':'Сбросить состав','CMP_NAVY18_PRESETS':'Ролевые шаблоны состава','CMP_NAVY18_PRESET_TT':'Шаблон только заполняет строки лучшими доступными корпусами для текущей эпохи. Создание выполняется отдельной кнопкой.',
      'CMP_NAVY18_RESULT_CREATED':'#P Один смешанный флот создан#!','CMP_NAVY18_RESULT_FAIL':'#N Флот не создан: проверьте порт, строки состава и технологии#!','CMP_NAVY18_RESULT_PRESET':'#P Шаблон загружен — проверьте пять строк перед созданием#!',
      'CMP_NAVY18_EXISTING_DESC':'Точный контекст флота подтверждён игровым тестом. Штатная карточка Victoria 3 остаётся основным мостом к существующему флоту; beta18 Final фиксирует проверенный точный флот, добавление кораблей и отсутствие скрытого резервного выбора.',
      'CMP_NAVY18_RUNTIME_NOTE':'beta18 Final: Fleet Composer 2.0 принят — пять произвольных строк собираются в один новый флот. Пользовательские Ship Templates по-прежнему применяются через штатный workflow Victoria 3.',
      'CMP_NAVY18_GROUP_COUNT':'Количество','CMP_NAVY18_INSTANT_DEFAULT_NOTE':'Мгновенное создание использует шаблон корпуса по умолчанию. Пользовательские шаблоны применяются через штатный Ship Designer и очередь строительства.',
      'CMP_NAVY18_NATIVE_TEMPLATE_NOTE':'Шаблонный маршрут: создайте шаблон в Ship Designer и используйте штатную очередь строительства нужного флота.'}
    else:
      vals={
      'CMP_NAVY18_MODE_NEW':'FLEET COMPOSER 2.0','CMP_NAVY18_MODE_EXISTING':'FLEET',
      'CMP_NAVY18_PORT_OPEN':'Choose port state','CMP_NAVY18_PORT_READY':'#P Port state selected#!','CMP_NAVY18_PORT_NONE':'#N Mark one of your own states with a port#!','CMP_NAVY18_PORT_TT':'The new fleet is created in a marked owned port state; if several are marked, the highest-GDP state is used.',
      'CMP_NAVY18_NEW_TITLE':'Fleet Composer 2.0','CMP_NAVY18_NEW_DESC':'Five independent rows. Each row can select any available hull from the full catalog and amount 0/1/3/5/10. All non-zero rows are assembled into one new fleet.',
      'CMP_NAVY18_COMP2_ROW':'Composition row','CMP_NAVY18_COMP2_SELECT_HULL':'Choose / change hull','CMP_NAVY18_COMP2_NO_HULL':'No hull selected','CMP_NAVY18_COMP2_BACK':'Back to composition','CMP_NAVY18_COMP2_PICK_TITLE':'Choose hull for row','CMP_NAVY18_COMP2_PICK_DESC':'All 25 combat hulls are available. Technology-locked choices stay visible but disabled. Repeating the same hull across rows is allowed and quantities accumulate.',
      'CMP_NAVY18_COMP2_READY':'#P Composition is ready#!','CMP_NAVY18_COMP2_BAD':'#N Check port, non-zero rows, selected hulls and technologies#!','CMP_NAVY18_COMP2_DUPLICATES':'The same hull may be repeated across rows; final quantities are additive.',
      'CMP_NAVY18_COMPOSITION':'New fleet composition','CMP_NAVY18_CREATE':'CREATE ONE FLEET','CMP_NAVY18_CREATE_TT':'The first non-zero row anchors a new fleet; remaining rows are added to that exact fleet in the same operation. Instant creation uses the type default template.',
      'CMP_NAVY18_CLEAR':'Reset composition','CMP_NAVY18_PRESETS':'Role composition presets','CMP_NAVY18_PRESET_TT':'A preset only fills rows with the best available hulls for the current era. Creation remains a separate action.',
      'CMP_NAVY18_RESULT_CREATED':'#P One mixed fleet created#!','CMP_NAVY18_RESULT_FAIL':'#N Fleet not created: check port, rows and technologies#!','CMP_NAVY18_RESULT_PRESET':'#P Preset loaded — review all five rows before creation#!',
      'CMP_NAVY18_EXISTING_DESC':'Exact fleet context passed runtime. Victoria 3 native fleet panel remains the bridge to existing fleets; beta18 Final freezes the verified exact targeting, add-ships and no-hidden-fallback contract.',
      'CMP_NAVY18_RUNTIME_NOTE':'beta18 Final: Fleet Composer 2.0 is accepted — five arbitrary rows assemble into one new fleet. User Ship Templates remain on Victoria 3 native workflow.',
      'CMP_NAVY18_GROUP_COUNT':'Count','CMP_NAVY18_INSTANT_DEFAULT_NOTE':'Instant creation uses the hull default template. User templates are applied through native Ship Designer and ship construction.',
      'CMP_NAVY18_NATIVE_TEMPLATE_NOTE':'Template-aware route: create a template in Ship Designer and use the native construction queue for the target fleet.'}
    for k,v in vals.items(): add(k,v)
    for r in range(1,cfg['composer2']['rows']+1): add(f'CMP_NAVY18_COMP2_ROW_{r}',('Строка' if ru else 'Row')+f' {r}')
    for a in cfg['composer2']['amounts']: add(f'CMP_NAVY18_COUNT_{a}',str(a))
    pnames={'escort':('Эскорт','Escort'),'battle':('Боевая группа','Battle Group'),'carrier':('Авианосная группа','Carrier Group'),'wolfpack':('Волчья стая','Wolfpack'),'amphibious':('Десантная поддержка','Amphibious Support')}
    for pid,(r,e) in pnames.items(): add(f'CMP_NAVY18_PRESET_{pid.upper()}',r if ru else e)
    return '\n'.join(L)+'\n'

def outputs():
    cfg,cat=load(); return {SGUI:generate_sgui(cfg,cat),EFFECT:generate_effects(cfg,cat),LOC_RU:generate_loc(cfg,cat,'russian'),LOC_EN:generate_loc(cfg,cat,'english')}
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); a=ap.parse_args(); stale=[]
    for p,t in outputs().items():
        enc='utf-8-sig'
        if a.check:
            if not p.exists() or p.read_text(encoding=enc)!=t: stale.append(str(p.relative_to(ROOT)))
        else: p.parent.mkdir(parents=True,exist_ok=True); p.write_text(t,encoding=enc)
    if a.check:
        if stale: print('STALE: '+', '.join(stale),file=sys.stderr); return 1
        print('PASS: beta18 Final Fleet Composer 2.0 codegen is deterministic'); return 0
    print('generated beta18 Final Fleet Composer 2.0')
    return 0
if __name__=='__main__': raise SystemExit(main())
