#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, re, hashlib
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
REG=ROOT/'registry/economy2.json'
GUI=ROOT/'gui/main/sakuya_main.gui'
MOD=ROOT/'common/static_modifiers/cmp_economy2_modifiers.txt'
SV=ROOT/'common/script_values/cmp_economy2_values.txt'
EFF=ROOT/'common/scripted_effects/cmp_economy2_effects.txt'
SGUI=ROOT/'common/scripted_guis/cmp_economy2_sgui.txt'
GEN=ROOT/'generated/economy2_popup.gui.txt'
BEGIN='# CMP_ECONOMY2_BEGIN popup'
END='# CMP_ECONOMY2_END popup'
ANCHOR='    # CMP v0.3 beta10 - Unified Target Controller popup (drawn after page content)'
HEADER='# AUTO-GENERATED by tools/generate_economy2.py. DO NOT EDIT BY HAND.\n'

def load(): return json.loads(REG.read_text(encoding='utf-8'))
def w(p,t,enc='utf-8'): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(t,encoding=enc)
def sha(t): return hashlib.sha256(t.encode()).hexdigest()

def static_modifiers(cfg):
    L=[HEADER.rstrip(),'# Economy 2.0 country modifiers']
    for p in cfg['parameters']:
        L += [f"{p['modifier']} = {{",f"    icon = \"gfx/interface/icons/timed_modifier_icons/{p['icon']}\"",f"    {p['modifier_key']} = 1","}",""]
    for p in cfg['policies']:
        L += [f"{p['modifier']} = {{",'    icon = "gfx/interface/icons/timed_modifier_icons/modifier_documents_positive.dds"',f"    {p['modifier_key']} = yes","}",""]
    return '\n'.join(L)

def script_values(cfg):
    L=[HEADER.rstrip(),'# Economy 2.0 reserve-cap-relative values']
    for x in cfg['money_steps_percent_of_reserve_cap']:
        L += [f"cmp_economy2_reserve_cap_{x} = {{",'    value = gold_reserves_limit',f"    multiply = {x/100:.2f}","}",""]
    return '\n'.join(L)

def apply_value_block(param, cfg, indent='    '):
    L=[]
    values=cfg['values']
    for i,v in enumerate(values,1):
        kw='if' if i==1 else 'else_if'
        L.append(f"{indent}{kw} = {{")
        L.append(f"{indent}    limit = {{ root.var:cmp_economy2_value_index = {i} }}")
        if abs(v['multiplier']) > 1e-12:
            L.append(f"{indent}    add_modifier = {{ name = {param['modifier']} multiplier = {v['multiplier']} }}")
            L.append(f"{indent}    set_variable = {{ name = cmp_economy2_state_{param['id']} value = {i} }}")
        else:
            L.append(f"{indent}    remove_variable = cmp_economy2_state_{param['id']}")
        L.append(f"{indent}}}")
    return L

def country_apply_helper(cfg):
    L=['cmp_economy2_apply_selected_to_country_effect = {']
    for i,p in enumerate(cfg['parameters'],1):
        kw='if' if i==1 else 'else_if'
        L += [f"    {kw} = {{",f"        limit = {{ root.var:cmp_economy2_parameter_index = {i} }}",f"        remove_modifier = {p['modifier']}"]
        L += apply_value_block(p,cfg,'        ')
        L += ['    }']
    L += ['}','','cmp_economy2_reset_selected_on_country_effect = {']
    for i,p in enumerate(cfg['parameters'],1):
        kw='if' if i==1 else 'else_if'
        L += [f"    {kw} = {{ limit = {{ root.var:cmp_economy2_parameter_index = {i} }} remove_modifier = {p['modifier']} remove_variable = cmp_economy2_state_{p['id']} }}"]
    L += ['}','','cmp_economy2_reset_all_on_country_effect = {']
    for p in cfg['parameters']:
        L += [f"    remove_modifier = {p['modifier']}",f"    remove_variable = cmp_economy2_state_{p['id']}"]
    for p in cfg['policies']:
        L += [f"    remove_modifier = {p['modifier']}",f"    remove_variable = cmp_economy2_policy_{p['id']}"]
    L += ['}']
    return L

def dispatch(action, success_code):
    # action is text executed in country scope; effect itself runs on player/root country.
    L=['    remove_variable = cmp_economy2_any_target','    remove_variable = cmp_economy2_feedback',
       '    if = {','        limit = { OR = { NOT = { has_variable = cmp_target_core_mode } var:cmp_target_core_mode = 1 } }',
       f'        {action}','        set_variable = cmp_economy2_any_target',f'        set_variable = {{ name = cmp_economy2_feedback value = {success_code} }}','    }',
       '    else_if = {','        limit = { var:cmp_target_core_mode = 2 }',
       '        every_country = { limit = { has_variable = sakuya_mark_country_target } '+action+' root = { set_variable = cmp_economy2_any_target } }',
       f'        if = {{ limit = {{ has_variable = cmp_economy2_any_target }} set_variable = {{ name = cmp_economy2_feedback value = {success_code} }} }}',
       '        else = { set_variable = { name = cmp_economy2_feedback value = -1 } }','    }']
    for mode,var in [(3,'cmp_target_group_a_member'),(4,'cmp_target_group_b_member'),(5,'cmp_target_group_c_member')]:
        L += ['    else_if = {',f'        limit = {{ var:cmp_target_core_mode = {mode} }}',
              f'        every_country = {{ limit = {{ has_variable = {var} }} {action} root = {{ set_variable = cmp_economy2_any_target }} }}',
              f'        if = {{ limit = {{ has_variable = cmp_economy2_any_target }} set_variable = {{ name = cmp_economy2_feedback value = {success_code} }} }}',
              '        else = { set_variable = { name = cmp_economy2_feedback value = -1 } }','    }']
    L += ['    else = { set_variable = { name = cmp_economy2_feedback value = -2 } }','    remove_variable = cmp_economy2_any_target']
    return L

def effects(cfg):
    L=[HEADER.rstrip(),'# Economy 2.0 explicit country-target operations','cmp_economy2_clear_feedback_effect = { remove_variable = cmp_economy2_feedback }']
    for i,p in enumerate(cfg['parameters'],1):
        L.append(f"cmp_economy2_select_parameter_{p['id']}_effect = {{ set_variable = {{ name = cmp_economy2_parameter_index value = {i} }} remove_variable = cmp_economy2_feedback }}")
    for i,v in enumerate(cfg['values'],1):
        L.append(f"cmp_economy2_select_value_{v['id']}_effect = {{ set_variable = {{ name = cmp_economy2_value_index value = {i} }} remove_variable = cmp_economy2_feedback }}")
    L += ['']+country_apply_helper(cfg)+['']
    L += ['cmp_economy2_apply_selected_effect = {']+dispatch('cmp_economy2_apply_selected_to_country_effect = yes',1)+['}']
    L += ['cmp_economy2_reset_selected_effect = {']+dispatch('cmp_economy2_reset_selected_on_country_effect = yes',2)+['}']
    L += ['cmp_economy2_reset_all_effect = {']+dispatch('cmp_economy2_reset_all_on_country_effect = yes',2)+['}']
    # Direct treasury and investment pool operations.
    for x in cfg['money_steps_percent_of_reserve_cap']:
        L += [f"cmp_economy2_treasury_add_{x}_effect = {{"]+dispatch(f"add_treasury = {{ value = gold_reserves_limit multiply = {x/100:.2f} }}",3)+['}']
        L += [f"cmp_economy2_investment_add_{x}_effect = {{"]+dispatch(f"add_investment_pool = cmp_economy2_reserve_cap_{x}",4)+['}']
    L += ['cmp_economy2_clear_debt_effect = {']+dispatch('clear_debt = yes',5)+['}']
    L += ['cmp_economy2_declare_bankruptcy_effect = {']+dispatch('clear_debt = yes remove_modifier = declared_bankruptcy add_modifier = { name = declared_bankruptcy months = 120 }',6)+['}']
    L += ['cmp_economy2_rescue_bankruptcy_effect = {']+dispatch('remove_modifier = declared_bankruptcy add_treasury = { value = gold_reserves_limit multiply = 1.0 }',7)+['}']
    # Ownership / economy policy toggles.
    for p in cfg['policies']:
        L += [f"cmp_economy2_policy_{p['id']}_enable_effect = {{"]+dispatch(f"remove_modifier = {p['modifier']} add_modifier = {{ name = {p['modifier']} }} set_variable = cmp_economy2_policy_{p['id']}",8)+['}']
        L += [f"cmp_economy2_policy_{p['id']}_disable_effect = {{"]+dispatch(f"remove_modifier = {p['modifier']} remove_variable = cmp_economy2_policy_{p['id']}",9)+['}']
    return '\n'.join(L)+'\n'

def target_valid_trigger():
    return 'OR = { AND = { OR = { NOT = { has_variable = cmp_target_core_mode } var:cmp_target_core_mode = 1 } is_player = yes } AND = { var:cmp_target_core_mode = 2 any_country = { has_variable = sakuya_mark_country_target } } AND = { var:cmp_target_core_mode = 3 any_country = { has_variable = cmp_target_group_a_member } } AND = { var:cmp_target_core_mode = 4 any_country = { has_variable = cmp_target_group_b_member } } AND = { var:cmp_target_core_mode = 5 any_country = { has_variable = cmp_target_group_c_member } } }'

def sgui(cfg):
    L=[HEADER.rstrip(),'# Economy 2.0 Scripted GUI endpoints',f"cmp_economy2_target_valid = {{ scope = country is_shown = {{ {target_valid_trigger()} }} }}",'cmp_economy2_target_scope_invalid = { scope = country is_shown = { OR = { var:cmp_target_core_mode = 6 var:cmp_target_core_mode = 7 var:cmp_target_core_mode = 8 var:cmp_target_core_mode = 9 var:cmp_target_core_mode = 10 var:cmp_target_core_mode = 11 } } }']
    for i,p in enumerate(cfg['parameters'],1):
        L += [f"cmp_economy2_parameter_{p['id']}_selected = {{ scope = country is_shown = {{ var:cmp_economy2_parameter_index = {i} }} }}",f"cmp_economy2_select_parameter_{p['id']} = {{ scope = country is_valid = {{ always = yes }} effect = {{ cmp_economy2_select_parameter_{p['id']}_effect = yes }} }}"]
    for i,v in enumerate(cfg['values'],1):
        L += [f"cmp_economy2_value_{v['id']}_selected = {{ scope = country is_shown = {{ var:cmp_economy2_value_index = {i} }} }}",f"cmp_economy2_select_value_{v['id']} = {{ scope = country is_valid = {{ always = yes }} effect = {{ cmp_economy2_select_value_{v['id']}_effect = yes }} }}"]
    valid=target_valid_trigger()
    L += [f"cmp_economy2_apply_selected = {{ scope = country is_valid = {{ {valid} has_variable = cmp_economy2_parameter_index has_variable = cmp_economy2_value_index }} effect = {{ cmp_economy2_apply_selected_effect = yes }} }}",
          f"cmp_economy2_reset_selected = {{ scope = country is_valid = {{ {valid} has_variable = cmp_economy2_parameter_index }} effect = {{ cmp_economy2_reset_selected_effect = yes }} }}",
          f"cmp_economy2_reset_all = {{ scope = country is_valid = {{ {valid} }} effect = {{ cmp_economy2_reset_all_effect = yes }} }}"]
    for x in cfg['money_steps_percent_of_reserve_cap']:
        L += [f"cmp_economy2_treasury_add_{x} = {{ scope = country is_valid = {{ {valid} }} effect = {{ cmp_economy2_treasury_add_{x}_effect = yes }} }}",f"cmp_economy2_investment_add_{x} = {{ scope = country is_valid = {{ {valid} }} effect = {{ cmp_economy2_investment_add_{x}_effect = yes }} }}"]
    L += [f"cmp_economy2_clear_debt = {{ scope = country is_valid = {{ {valid} }} effect = {{ cmp_economy2_clear_debt_effect = yes }} }}",f"cmp_economy2_declare_bankruptcy = {{ scope = country is_valid = {{ {valid} }} effect = {{ cmp_economy2_declare_bankruptcy_effect = yes }} }}",f"cmp_economy2_rescue_bankruptcy = {{ scope = country is_valid = {{ {valid} }} effect = {{ cmp_economy2_rescue_bankruptcy_effect = yes }} }}"]
    for p in cfg['policies']:
        L += [f"cmp_economy2_policy_{p['id']}_enable = {{ scope = country is_valid = {{ {valid} }} effect = {{ cmp_economy2_policy_{p['id']}_enable_effect = yes }} }}",f"cmp_economy2_policy_{p['id']}_disable = {{ scope = country is_valid = {{ {valid} }} effect = {{ cmp_economy2_policy_{p['id']}_disable_effect = yes }} }}"]
    for code,name in [(1,'applied'),(2,'reset'),(3,'treasury'),(4,'investment'),(5,'debt'),(6,'bankruptcy'),(7,'rescue'),(8,'policy_on'),(9,'policy_off'),(-1,'no_target'),(-2,'wrong_scope')]:
        L.append(f"cmp_economy2_feedback_{name} = {{ scope = country is_shown = {{ var:cmp_economy2_feedback = {code} }} }}")
    return '\n'.join(L)+'\n'

def button(label,sgui,x,y,w=180,tt='CMP_ECO2_TT_GENERIC',selected=None,color='{ 0.42 0.50 0.62 0.96 }',h=48,font=14):
    sel=''
    if selected:
        sel=f''' icon = {{ visible = "[GetScriptedGui('{selected}').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" position = {{ 4 {h-5} }} size = {{ {w-8} 3 }} color = {{ 0.35 0.95 0.45 1 }} texture = "gfx/interface/buttons/expand_button_bg_dropdown.dds" alwaystransparent = yes }}'''
    return f'''        widget = {{ position = {{ {x} {y} }} size = {{ {w} {h} }}
            button_standard = {{ size = {{ {w} {h} }} enabled = "[GetScriptedGui('{sgui}').IsValid(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" onclick = "[GetScriptedGui('{sgui}').Execute(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" tooltip = "{tt}" blockoverride "primary_visible" {{}} blockoverride "primary_texture" {{ texture = "gfx/interface/buttons/expand_button_bg_dropdown.dds" color = {color} }} textbox = {{ size = {{ {w-12} {h-8} }} parentanchor = center maximumsize = {{ {w-12} {h-8} }} fontsize = {font} fontsize_min = 11 align = center|nobaseline elide = right text = "{label}" }} }}{sel}
        }}'''

def ui_button(label,onclick,x,y,w=240,h=48,color='{ 0.42 0.55 0.72 0.96 }',font=14,tt='CMP_ECO2_TT_GENERIC'):
    actions = onclick if isinstance(onclick, (list, tuple)) else [onclick]
    onclick_fields = ' '.join(f'onclick = "{action}"' for action in actions)
    return f'''        button_standard = {{ position = {{ {x} {y} }} size = {{ {w} {h} }} {onclick_fields} tooltip = "{tt}" blockoverride "primary_visible" {{}} blockoverride "primary_texture" {{ texture = "gfx/interface/buttons/expand_button_bg_dropdown.dds" color = {color} }} textbox = {{ size = {{ {w-12} {h-8} }} parentanchor = center maximumsize = {{ {w-12} {h-8} }} fontsize = {font} fontsize_min = 11 align = center|nobaseline elide = right text = "{label}" }} }}'''

def eco_tab(label,val,x):
    visible = f"[Or(Not(GetVariableSystem.Exists('cmp_economy2_tab')), GetVariableSystem.HasValue('cmp_economy2_tab', '{val}'))]" if val == 'direct' else f"[GetVariableSystem.HasValue('cmp_economy2_tab', '{val}')]"
    return ui_button(label,f"[GetVariableSystem.Set('cmp_economy2_tab', '{val}')]",x,118,320,48,'{ 0.40 0.53 0.68 0.97 }',14,'CMP_ECO2_TT_GENERIC') + f'''\n        icon = {{ visible = "{visible}" position = {{ {x+6} 162 }} size = {{ 308 4 }} color = {{ 0.35 0.95 0.45 1 }} texture = "gfx/interface/buttons/expand_button_bg_dropdown.dds" alwaystransparent = yes }}'''

def popup(cfg):
    L=[BEGIN,
       '    # Economy 2.0 emergency popup retained without a visible legacy-workspace entry - beta15.3.1',
       '    widget = {',
       '        name = "cmp_economy2_popup"',
       '        visible = "[GetVariableSystem.Exists(\'cmp_economy2_panel\')]"',
       '        position = { 82 42 }',
       '        size = { 1040 700 }',
       '        icon = { size = { 1040 700 } texture = "gfx/interface/backgrounds/big_header_pattern.dds" color = { 0.055 0.065 0.09 0.995 } }',
       '        icon = { position = { 2 2 } size = { 1036 696 } texture = "gfx/interface/buttons/expand_button_bg_dropdown.dds" color = { 0.17 0.20 0.26 0.95 } alwaystransparent = yes }',
       '        textbox = { position = { 22 12 } size = { 720 34 } maximumsize = { 720 34 } fontsize = 22 fontsize_min = 16 align = left text = "CMP_ECO2_TITLE" }',
       '        close_button = { position = { 988 10 } size = { 40 40 } onclick = "[GetVariableSystem.Clear(\'cmp_economy2_panel\')]" }',
       '        textbox = { position = { 22 48 } size = { 720 46 } maximumsize = { 720 46 } fontsize = 13 fontsize_min = 11 align = left text = "CMP_ECO2_DESC" }',
       ui_button('CMP_ECO2_OPEN_TARGETS',["[GetVariableSystem.Set('cmp_workspace_page', 'target')]", "[GetVariableSystem.Set('cmp_workspace_shell', 'open')]"],776,50,238,48,'{ 0.45 0.62 0.82 0.97 }',14,'CMP_ECO2_TARGET_TT'),
       '        textbox = { position = { 776 96 } visible = "[GetScriptedGui(\'cmp_economy2_target_valid\').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" size = { 238 22 } maximumsize = { 238 22 } fontsize = 12 fontsize_min = 11 align = center text = "CMP_ECO2_TARGET_OK" }',
       '        textbox = { position = { 776 96 } visible = "[Not(GetScriptedGui(\'cmp_economy2_target_valid\').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End))]" size = { 238 22 } maximumsize = { 238 22 } fontsize = 12 fontsize_min = 11 align = center text = "CMP_ECO2_TARGET_BAD" }',
       eco_tab('CMP_ECO2_DIRECT_TITLE','direct',22),
       eco_tab('CMP_ECO2_MOD_TITLE','modifiers',360),
       eco_tab('CMP_ECO2_POLICY_TITLE','policies',698),
    ]

    # Direct money/debt operations tab.
    L += ['        widget = { visible = "[Or(Not(GetVariableSystem.Exists(\'cmp_economy2_tab\')), GetVariableSystem.HasValue(\'cmp_economy2_tab\', \'direct\'))]" position = { 22 184 } size = { 992 430 }',
          '            textbox = { size = { 960 30 } maximumsize = { 960 30 } fontsize = 17 fontsize_min = 13 align = left text = "CMP_ECO2_DIRECT_TITLE" }',
          '            textbox = { position = { 0 34 } size = { 960 42 } maximumsize = { 960 42 } fontsize = 13 fontsize_min = 11 align = left text = "CMP_ECO2_DIRECT_DESC" }',
          '            textbox = { position = { 0 90 } size = { 140 30 } maximumsize = { 140 30 } fontsize = 15 fontsize_min = 12 align = left text = "CMP_ECO2_TREASURY" }']
    x=152
    for step in cfg['money_steps_percent_of_reserve_cap']:
        L.append(button(f'CMP_ECO2_CAP_{step}',f'cmp_economy2_treasury_add_{step}',x,82,194,'CMP_ECO2_TT_TREASURY')); x+=202
    L += ['            textbox = { position = { 0 150 } size = { 140 30 } maximumsize = { 140 30 } fontsize = 15 fontsize_min = 12 align = left text = "CMP_ECO2_INVESTMENT" }']
    x=152
    for step in cfg['money_steps_percent_of_reserve_cap']:
        L.append(button(f'CMP_ECO2_CAP_{step}',f'cmp_economy2_investment_add_{step}',x,142,194,'CMP_ECO2_TT_INVESTMENT')); x+=202
    L += ['            textbox = { position = { 0 214 } size = { 960 30 } maximumsize = { 960 30 } fontsize = 16 fontsize_min = 12 align = left text = "CMP_ECO2_DEBT_SECTION" }']
    L.append(button('CMP_ECO2_CLEAR_DEBT','cmp_economy2_clear_debt',0,252,300,'CMP_ECO2_TT_CLEAR_DEBT',None,'{ 0.42 0.62 0.48 0.96 }',52,14))
    L.append(button('CMP_ECO2_BANKRUPTCY','cmp_economy2_declare_bankruptcy',314,252,300,'CMP_ECO2_TT_BANKRUPTCY',None,'{ 0.72 0.38 0.42 0.96 }',52,14))
    L.append(button('CMP_ECO2_RESCUE','cmp_economy2_rescue_bankruptcy',628,252,332,'CMP_ECO2_TT_RESCUE',None,'{ 0.46 0.64 0.50 0.96 }',52,14))
    L += ['        }']

    # Economic modifiers tab: larger 3-column parameter selector and 2-row value selector.
    L += ['        widget = { visible = "[GetVariableSystem.HasValue(\'cmp_economy2_tab\', \'modifiers\')]" position = { 22 184 } size = { 992 500 }',
          '            textbox = { size = { 960 30 } maximumsize = { 960 30 } fontsize = 17 fontsize_min = 13 align = left text = "CMP_ECO2_MOD_TITLE" }',
          '            textbox = { position = { 0 34 } size = { 960 42 } maximumsize = { 960 42 } fontsize = 13 fontsize_min = 11 align = left text = "CMP_ECO2_MOD_DESC" }']
    for idx,p in enumerate(cfg['parameters']):
        row=idx//3; col=idx%3; x=col*324; y=84+row*54
        L.append(button(p['loc_key'],f"cmp_economy2_select_parameter_{p['id']}",x,y,312,'CMP_ECO2_TT_PARAM',f"cmp_economy2_parameter_{p['id']}_selected",'{ 0.42 0.55 0.72 0.96 }',48,13))
    L += ['            textbox = { position = { 0 304 } size = { 960 28 } maximumsize = { 960 28 } fontsize = 16 fontsize_min = 12 align = left text = "CMP_ECO2_VALUE_TITLE" }']
    first=cfg['values'][:5]; second=cfg['values'][5:]
    for idx,v in enumerate(first):
        L.append(button(f"CMP_ECO2_VALUE_{v['id'].upper()}",f"cmp_economy2_select_value_{v['id']}",idx*194,338,184,'CMP_ECO2_TT_VALUE',f"cmp_economy2_value_{v['id']}_selected",'{ 0.42 0.50 0.62 0.96 }',46,13))
    for idx,v in enumerate(second):
        L.append(button(f"CMP_ECO2_VALUE_{v['id'].upper()}",f"cmp_economy2_select_value_{v['id']}",idx*242,392,232,'CMP_ECO2_TT_VALUE',f"cmp_economy2_value_{v['id']}_selected",'{ 0.42 0.50 0.62 0.96 }',46,13))
    L.append(button('CMP_ECO2_APPLY','cmp_economy2_apply_selected',0,446,310,'CMP_ECO2_TT_APPLY',None,'{ 0.38 0.68 0.44 0.96 }',52,15))
    L.append(button('CMP_ECO2_RESET_SELECTED','cmp_economy2_reset_selected',324,446,310,'CMP_ECO2_TT_RESET_SELECTED',None,'{ 0.64 0.52 0.32 0.96 }',52,14))
    L.append(button('CMP_ECO2_RESET_ALL','cmp_economy2_reset_all',648,446,312,'CMP_ECO2_TT_RESET_ALL',None,'{ 0.72 0.38 0.42 0.96 }',52,14))
    L += ['        }']

    # Ownership/policy tab: one readable row per policy.
    L += ['        widget = { visible = "[GetVariableSystem.HasValue(\'cmp_economy2_tab\', \'policies\')]" position = { 22 184 } size = { 992 452 }',
          '            textbox = { size = { 960 30 } maximumsize = { 960 30 } fontsize = 17 fontsize_min = 13 align = left text = "CMP_ECO2_POLICY_TITLE" }',
          '            textbox = { position = { 0 34 } size = { 960 44 } maximumsize = { 960 44 } fontsize = 13 fontsize_min = 11 align = left text = "CMP_ECO2_POLICY_DESC" }']
    for idx,p in enumerate(cfg['policies']):
        y=86+idx*58
        L.append(f'            textbox = {{ position = {{ 0 {y+10} }} size = {{ 650 30 }} maximumsize = {{ 650 30 }} fontsize = 14 fontsize_min = 11 align = left elide = right text = "{p["loc_key"]}" }}')
        L.append(button('CMP_ECO2_ON',f"cmp_economy2_policy_{p['id']}_enable",672,y,132,'CMP_ECO2_TT_POLICY_ON',None,'{ 0.38 0.68 0.44 0.96 }',48,14))
        L.append(button('CMP_ECO2_OFF',f"cmp_economy2_policy_{p['id']}_disable",818,y,142,'CMP_ECO2_TT_POLICY_OFF',None,'{ 0.68 0.42 0.44 0.96 }',48,14))
    L += ['        }']

    feedback=[('applied','CMP_ECO2_FB_APPLIED'),('reset','CMP_ECO2_FB_RESET'),('treasury','CMP_ECO2_FB_TREASURY'),('investment','CMP_ECO2_FB_INVESTMENT'),('debt','CMP_ECO2_FB_DEBT'),('bankruptcy','CMP_ECO2_FB_BANKRUPTCY'),('rescue','CMP_ECO2_FB_RESCUE'),('policy_on','CMP_ECO2_FB_POLICY_ON'),('policy_off','CMP_ECO2_FB_POLICY_OFF'),('no_target','CMP_ECO2_FB_NO_TARGET'),('wrong_scope','CMP_ECO2_FB_WRONG_SCOPE')]
    for name,key in feedback:
        L.append(f'        textbox = {{ position = {{ 22 652 }} visible = "[GetScriptedGui(\'cmp_economy2_feedback_{name}\').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)]" size = {{ 992 28 }} maximumsize = {{ 992 28 }} fontsize = 13 fontsize_min = 11 align = center text = "{key}" }}')
    L += ['    }',END]
    return '\n'.join(L)+'\n'

def patch_gui(block):
    text=GUI.read_text(encoding='utf-8-sig')
    if BEGIN in text and END in text:
        a=text.index(BEGIN); b=text.index(END,a)+len(END)
        text=text[:a]+block.rstrip()+text[b:]
    else:
        if ANCHOR not in text: raise RuntimeError('Target popup anchor not found')
        text=text.replace(ANCHOR,block.rstrip()+'\n\n'+ANCHOR,1)
    return text

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); args=ap.parse_args(); cfg=load()
    outputs={MOD:static_modifiers(cfg),SV:script_values(cfg),EFF:effects(cfg),SGUI:sgui(cfg)}
    block=popup(cfg); outputs[GEN]=block; gui_text=patch_gui(block)
    if args.check:
        stale=[]
        for p,t in outputs.items():
            if not p.exists() or p.read_text(encoding='utf-8-sig',errors='replace')!=t: stale.append(str(p.relative_to(ROOT)))
        current=GUI.read_text(encoding='utf-8-sig',errors='replace')
        if current!=gui_text: stale.append(str(GUI.relative_to(ROOT)))
        if stale:
            print('STALE',*stale,sep='\n'); return 1
        print('PASS economy2 codegen deterministic'); return 0
    for p,t in outputs.items(): w(p,t)
    w(GUI,gui_text,'utf-8-sig')
    print(json.dumps({'status':'generated','parameters':len(cfg['parameters']),'values':len(cfg['values']),'policies':len(cfg['policies']),'money_steps':cfg['money_steps_percent_of_reserve_cap'],'gui_sha256':sha(gui_text)},ensure_ascii=False))
    return 0
if __name__=='__main__': raise SystemExit(main())
