#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
REG=ROOT/'registry/navy18.json'
SGUI=ROOT/'common/scripted_guis/cmp_navy18_transfer_sgui.txt'
EFFECT=ROOT/'common/scripted_effects/cmp_navy18_transfer_effects.txt'
LOC_RU=ROOT/'localization/russian/cmp_navy18_transfer_l_russian.yml'
LOC_EN=ROOT/'localization/english/cmp_navy18_transfer_l_english.yml'
HEADER='# AUTO-GENERATED by tools/generate_navy18_transfer.py. DO NOT EDIT BY HAND.\n'

def load(): return json.loads(REG.read_text(encoding='utf-8'))

def receiver_ready() -> str:
    return 'owner = { any_country = { has_variable = sakuya_mark_country_target NOT = { is_player = yes } has_port_country = yes } }'

def exact_eligible() -> str:
    return 'any_scope_ship = { has_variable = cmp_navy18_exact_ship_target hit_points > 0 NOT = { is_in_battle = yes } NOT = { is_flagship = yes } }'

def basket_exists() -> str:
    return 'owner = { any_scope_fleet = { any_scope_ship = { has_variable = cmp_navy18_transfer_batch_target } } }'

def basket_valid() -> str:
    return 'owner = { NOT = { any_scope_fleet = { any_scope_ship = { has_variable = cmp_navy18_transfer_batch_target OR = { NOT = { hit_points > 0 } is_in_battle = yes is_flagship = yes } } } } }'

def generate_sgui(cfg:dict)->str:
    t=cfg['transfer']; max_batch=t['batch_max']
    L=[HEADER.rstrip(),'# beta18 Final exact ship transfer: exact Ship marker + marked receiver country + optional persistent batch basket.']
    L += [
      f'cmp_navy18_transfer_receiver_ready = {{ scope = military_formation is_shown = {{ {receiver_ready()} }} }}',
      'cmp_navy18_transfer_receiver_missing = { scope = military_formation is_shown = { owner = { NOT = { any_country = { has_variable = sakuya_mark_country_target } } } } }',
      'cmp_navy18_transfer_receiver_self = { scope = military_formation is_shown = { owner = { any_country = { has_variable = sakuya_mark_country_target is_player = yes } } } }',
      'cmp_navy18_transfer_receiver_no_port = { scope = military_formation is_shown = { owner = { any_country = { has_variable = sakuya_mark_country_target NOT = { is_player = yes } NOT = { has_port_country = yes } } } } }',
      f'cmp_navy18_transfer_exact_eligible = {{ scope = military_formation is_shown = {{ owner = {{ is_player = yes }} {exact_eligible()} }} }}',
      'cmp_navy18_transfer_exact_in_batch = { scope = military_formation is_shown = { any_scope_ship = { has_variable = cmp_navy18_exact_ship_target has_variable = cmp_navy18_transfer_batch_target } } }',
      f'cmp_navy18_transfer_has_batch = {{ scope = military_formation is_shown = {{ {basket_exists()} }} }}',
      f'cmp_navy18_transfer_batch_valid = {{ scope = military_formation is_shown = {{ {basket_exists()} {basket_valid()} }} }}',
      f'cmp_navy18_transfer_batch_invalid = {{ scope = military_formation is_shown = {{ {basket_exists()} NOT = {{ {basket_valid()} }} }} }}',
      f'cmp_navy18_transfer_add_exact = {{ scope = military_formation is_valid = {{ owner = {{ is_player = yes OR = {{ NOT = {{ has_variable = cmp_navy18_transfer_batch_count }} var:cmp_navy18_transfer_batch_count < {max_batch} }} }} {exact_eligible()} NOT = {{ any_scope_ship = {{ has_variable = cmp_navy18_exact_ship_target has_variable = cmp_navy18_transfer_batch_target }} }} }} effect = {{ cmp_navy18_transfer_add_exact_effect = yes }} }}',
      'cmp_navy18_transfer_remove_exact = { scope = military_formation is_valid = { owner = { is_player = yes } any_scope_ship = { has_variable = cmp_navy18_exact_ship_target has_variable = cmp_navy18_transfer_batch_target } } effect = { cmp_navy18_transfer_remove_exact_effect = yes } }',
      f'cmp_navy18_transfer_clear_batch = {{ scope = military_formation is_valid = {{ owner = {{ is_player = yes }} {basket_exists()} }} effect = {{ cmp_navy18_transfer_clear_batch_effect = yes }} }}',
      f'cmp_navy18_transfer_single = {{ scope = military_formation is_valid = {{ owner = {{ is_player = yes }} {receiver_ready()} {exact_eligible()} }} effect = {{ cmp_navy18_transfer_single_effect = yes }} }}',
      f'cmp_navy18_transfer_batch = {{ scope = military_formation is_valid = {{ owner = {{ is_player = yes }} {receiver_ready()} {basket_exists()} {basket_valid()} }} effect = {{ cmp_navy18_transfer_batch_effect = yes }} }}',
      'cmp_navy18_transfer_result_added = { scope = military_formation is_shown = { owner = { var:cmp_navy18_transfer_result = 1 } } }',
      'cmp_navy18_transfer_result_removed = { scope = military_formation is_shown = { owner = { var:cmp_navy18_transfer_result = 2 } } }',
      'cmp_navy18_transfer_result_single = { scope = military_formation is_shown = { owner = { var:cmp_navy18_transfer_result = 3 } } }',
      'cmp_navy18_transfer_result_batch = { scope = military_formation is_shown = { owner = { var:cmp_navy18_transfer_result = 4 } } }',
      'cmp_navy18_transfer_result_cleared = { scope = military_formation is_shown = { owner = { var:cmp_navy18_transfer_result = 5 } } }',
    ]
    for n in range(1,max_batch+1):
        L.append(f'cmp_navy18_transfer_batch_count_{n} = {{ scope = military_formation is_shown = {{ owner = {{ var:cmp_navy18_transfer_batch_count = {n} }} }} }}')
    L.append('')
    return '\n'.join(L)

def generate_effects(cfg:dict)->str:
    max_batch=cfg['transfer']['batch_max']
    L=[HEADER.rstrip(),'# Public 1.13 contract: set_ship_owner for one Ship; set_ship_owner_multiple for batches; clear_ownership_transfer_fleet on source country after batch.']
    L += [
      'cmp_navy18_transfer_clear_result_effect = { owner = { remove_variable = cmp_navy18_transfer_result } }',
      'cmp_navy18_transfer_add_exact_effect = {',
      '    cmp_navy18_transfer_clear_result_effect = yes',
      '    every_scope_ship = {',
      '        limit = { has_variable = cmp_navy18_exact_ship_target hit_points > 0 NOT = { is_in_battle = yes } NOT = { is_flagship = yes } NOT = { has_variable = cmp_navy18_transfer_batch_target } }',
      '        set_variable = cmp_navy18_transfer_batch_target',
      '    }',
      '    owner = {',
      '        if = { limit = { NOT = { has_variable = cmp_navy18_transfer_batch_count } } set_variable = { name = cmp_navy18_transfer_batch_count value = 1 } }',
      f'        else_if = {{ limit = {{ var:cmp_navy18_transfer_batch_count < {max_batch} }} change_variable = {{ name = cmp_navy18_transfer_batch_count add = 1 }} }}',
      '        set_variable = { name = cmp_navy18_transfer_result value = 1 }',
      '    }',
      '}',
      'cmp_navy18_transfer_remove_exact_effect = {',
      '    cmp_navy18_transfer_clear_result_effect = yes',
      '    every_scope_ship = { limit = { has_variable = cmp_navy18_exact_ship_target has_variable = cmp_navy18_transfer_batch_target } remove_variable = cmp_navy18_transfer_batch_target }',
      '    owner = {',
      '        if = { limit = { has_variable = cmp_navy18_transfer_batch_count } change_variable = { name = cmp_navy18_transfer_batch_count add = -1 } }',
      '        if = { limit = { has_variable = cmp_navy18_transfer_batch_count var:cmp_navy18_transfer_batch_count <= 0 } remove_variable = cmp_navy18_transfer_batch_count }',
      '        set_variable = { name = cmp_navy18_transfer_result value = 2 }',
      '    }',
      '}',
      'cmp_navy18_transfer_clear_batch_effect = {',
      '    owner = {',
      '        every_scope_fleet = { every_scope_ship = { limit = { has_variable = cmp_navy18_transfer_batch_target } remove_variable = cmp_navy18_transfer_batch_target } }',
      '        remove_variable = cmp_navy18_transfer_batch_count',
      '        set_variable = { name = cmp_navy18_transfer_result value = 5 }',
      '    }',
      '}',
      'cmp_navy18_transfer_resolve_receiver_effect = {',
      '    owner = {',
      '        every_country = {',
      '            limit = { has_variable = sakuya_mark_country_target NOT = { is_player = yes } has_port_country = yes }',
      '            save_temporary_scope_as = cmp_navy18_transfer_receiver',
      '        }',
      '    }',
      '}',
      'cmp_navy18_transfer_single_effect = {',
      '    save_temporary_scope_as = cmp_navy18_transfer_source_fleet',
      '    owner = { save_temporary_scope_as = cmp_navy18_transfer_source_country remove_variable = cmp_navy18_transfer_result }',
      '    cmp_navy18_transfer_resolve_receiver_effect = yes',
      '    if = {',
      '        limit = { exists = scope:cmp_navy18_transfer_receiver any_scope_ship = { has_variable = cmp_navy18_exact_ship_target hit_points > 0 NOT = { is_in_battle = yes } NOT = { is_flagship = yes } } }',
      '        every_scope_ship = {',
      '            limit = { has_variable = cmp_navy18_exact_ship_target hit_points > 0 NOT = { is_in_battle = yes } NOT = { is_flagship = yes } }',
      '            if = {',
      '                limit = { has_variable = cmp_navy18_transfer_batch_target }',
      '                remove_variable = cmp_navy18_transfer_batch_target',
      '                scope:cmp_navy18_transfer_source_country = {',
      '                    if = { limit = { has_variable = cmp_navy18_transfer_batch_count } change_variable = { name = cmp_navy18_transfer_batch_count add = -1 } }',
      '                    if = { limit = { has_variable = cmp_navy18_transfer_batch_count var:cmp_navy18_transfer_batch_count <= 0 } remove_variable = cmp_navy18_transfer_batch_count }',
      '                }',
      '            }',
      '            remove_variable = cmp_navy18_exact_ship_target',
      '            set_ship_owner = scope:cmp_navy18_transfer_receiver',
      '        }',
      '        remove_variable = cmp_navy18_exact_ship_slot',
      '        scope:cmp_navy18_transfer_source_country = { set_variable = { name = cmp_navy18_transfer_result value = 3 } }',
      '    }',
      '}',
      'cmp_navy18_transfer_batch_effect = {',
      '    owner = { save_temporary_scope_as = cmp_navy18_transfer_source_country remove_variable = cmp_navy18_transfer_result }',
      '    cmp_navy18_transfer_resolve_receiver_effect = yes',
      '    if = {',
      '        limit = {',
      '            exists = scope:cmp_navy18_transfer_receiver',
      '            owner = { any_scope_fleet = { any_scope_ship = { has_variable = cmp_navy18_transfer_batch_target } } }',
      '            owner = { NOT = { any_scope_fleet = { any_scope_ship = { has_variable = cmp_navy18_transfer_batch_target OR = { NOT = { hit_points > 0 } is_in_battle = yes is_flagship = yes } } } } }',
      '        }',
      '        cmp_navy18_shipctrl_clear_owner_marks_effect = yes',
      '        scope:cmp_navy18_transfer_source_country = {',
      '            every_scope_fleet = {',
      '                every_scope_ship = {',
      '                    limit = { has_variable = cmp_navy18_transfer_batch_target hit_points > 0 NOT = { is_in_battle = yes } NOT = { is_flagship = yes } }',
      '                    remove_variable = cmp_navy18_transfer_batch_target',
      '                    set_ship_owner_multiple = scope:cmp_navy18_transfer_receiver',
      '                }',
      '            }',
      '            clear_ownership_transfer_fleet = yes',
      '            remove_variable = cmp_navy18_transfer_batch_count',
      '            set_variable = { name = cmp_navy18_transfer_result value = 4 }',
      '        }',
      '    }',
      '}',
      ''
    ]
    return '\n'.join(L)

def generate_loc(cfg:dict,lang:str)->str:
    ru=lang=='russian'; L=['l_russian:' if ru else 'l_english:']; add=lambda k,v:L.append(f' {k}:0 "{v}"')
    if ru:
        vals={
          'CMP_NAVY18_MODE_TRANSFER':'ПЕРЕДАЧА',
          'CMP_NAVY18_TRANSFER_TITLE':'Передача кораблей другой державе',
          'CMP_NAVY18_TRANSFER_DESC':'Получатель — текущая отмеченная страна. Точный корабль берётся из вкладки «Корабли». Для пакетной передачи добавляйте до 20 точных кораблей в список; они могут находиться в разных ваших флотах.',
          'CMP_NAVY18_TRANSFER_RECEIVER':'Получатель',
          'CMP_NAVY18_TRANSFER_OPEN_TARGETS':'ЦЕЛИ / ПОЛУЧАТЕЛЬ',
          'CMP_NAVY18_TRANSFER_RECEIVER_TT':'Чтобы выбрать получателя: щёлкните нужную страну правой кнопкой и используйте дипломатическое действие «Отметить страну». Затем вернитесь сюда. Получателю нужен хотя бы один порт.',
          'CMP_NAVY18_TRANSFER_RECEIVER_READY':'#P Отмеченная страна готова принять корабли#!',
          'CMP_NAVY18_TRANSFER_RECEIVER_MISSING':'#N Получатель не выбран: отметьте другую страну#!',
          'CMP_NAVY18_TRANSFER_RECEIVER_SELF':'#N Нельзя передавать корабли самому себе#!',
          'CMP_NAVY18_TRANSFER_RECEIVER_NO_PORT':'#N У отмеченной страны нет порта#!',
          'CMP_NAVY18_TRANSFER_EXACT_TITLE':'Точный корабль',
          'CMP_NAVY18_TRANSFER_EXACT_READY':'#P Выбранный корабль доступен для передачи#!',
          'CMP_NAVY18_TRANSFER_EXACT_BAD':'#N Выберите исправный корабль вне боя; флагман сначала нужно снять#!',
          'CMP_NAVY18_TRANSFER_ADD_BATCH':'Добавить в список',
          'CMP_NAVY18_TRANSFER_REMOVE_BATCH':'Убрать из списка',
          'CMP_NAVY18_TRANSFER_BATCH_TT':'Список хранится на конкретных выбранных кораблях и сохраняется при переключении между вашими флотами. Максимум 20 кораблей.',
          'CMP_NAVY18_TRANSFER_BATCH_TITLE':'Пакет передачи',
          'CMP_NAVY18_TRANSFER_BATCH_EMPTY':'Список передачи пуст',
          'CMP_NAVY18_TRANSFER_BATCH_READY':'#P Список готов к пакетной передаче#!',
          'CMP_NAVY18_TRANSFER_BATCH_INVALID':'#N В списке появился корабль в бою, флагман или недействительная цель#!',
          'CMP_NAVY18_TRANSFER_BATCH_COUNT':'Кораблей в списке: ',
          'CMP_NAVY18_TRANSFER_CLEAR_BATCH':'Очистить список',
          'CMP_NAVY18_TRANSFER_SINGLE':'ПЕРЕДАТЬ ТОЧНЫЙ КОРАБЛЬ',
          'CMP_NAVY18_TRANSFER_BATCH':'ПЕРЕДАТЬ ВЕСЬ СПИСОК',
          'CMP_NAVY18_TRANSFER_SINGLE_TT':'Передаёт только текущий выбранный корабль. Корабль в бою и флагман блокируются.',
          'CMP_NAVY18_TRANSFER_BATCH_ACTION_TT':'Передаёт все корабли из списка одной пакетной операцией, затем очищает временный флот передачи владения на стороне источника, как требует механизм Victoria 3 1.13.',
          'CMP_NAVY18_TRANSFER_WARNING':'#Y Передача меняет владельца корабля. Перед нажатием проверьте отмеченную страну и список. После пакетной передачи временный флот передачи владения у источника автоматически очищается.#!',
          'CMP_NAVY18_TRANSFER_RESULT_ADDED':'#P Корабль добавлен в список передачи#!',
          'CMP_NAVY18_TRANSFER_RESULT_REMOVED':'#P Корабль удалён из списка передачи#!',
          'CMP_NAVY18_TRANSFER_RESULT_SINGLE':'#P Команда передачи точного корабля выполнена — проверьте флот получателя#!',
          'CMP_NAVY18_TRANSFER_RESULT_BATCH':'#P Пакетная передача выполнена — проверьте флоты источника и получателя#!',
          'CMP_NAVY18_TRANSFER_RESULT_CLEARED':'Список передачи очищен',
          'CMP_NAVY18_TRANSFER_SCOPE_NOTE':'beta18 Final: одиночная и пакетная передача, включая несколько исходных флотов, блокировки боя/флагмана и очистку временного transfer-fleet, подтверждены полным regression.'
        }
    else:
        vals={
          'CMP_NAVY18_MODE_TRANSFER':'TRANSFER',
          'CMP_NAVY18_TRANSFER_TITLE':'Transfer ships to another country',
          'CMP_NAVY18_TRANSFER_DESC':'The receiver is the currently marked country. The exact ship comes from the Ships tab. For a batch, add up to 20 exact ships to the basket; they may come from different player fleets.',
          'CMP_NAVY18_TRANSFER_RECEIVER':'Receiver',
          'CMP_NAVY18_TRANSFER_OPEN_TARGETS':'TARGETS / RECEIVER',
          'CMP_NAVY18_TRANSFER_RECEIVER_TT':'To choose a receiver, right-click the target country and use the Mark Country diplomatic action, then return here. The receiver must have at least one port.',
          'CMP_NAVY18_TRANSFER_RECEIVER_READY':'#P Marked country can receive ships#!',
          'CMP_NAVY18_TRANSFER_RECEIVER_MISSING':'#N No receiver: mark another country#!',
          'CMP_NAVY18_TRANSFER_RECEIVER_SELF':'#N Ships cannot be transferred to yourself#!',
          'CMP_NAVY18_TRANSFER_RECEIVER_NO_PORT':'#N The marked country has no port#!',
          'CMP_NAVY18_TRANSFER_EXACT_TITLE':'Exact ship',
          'CMP_NAVY18_TRANSFER_EXACT_READY':'#P Selected ship is eligible for transfer#!',
          'CMP_NAVY18_TRANSFER_EXACT_BAD':'#N Select a living ship out of battle; unset flagship first#!',
          'CMP_NAVY18_TRANSFER_ADD_BATCH':'Add to basket',
          'CMP_NAVY18_TRANSFER_REMOVE_BATCH':'Remove from basket',
          'CMP_NAVY18_TRANSFER_BATCH_TT':'The basket is stored on exact Ship objects and persists while switching between your fleets. Maximum 20 ships.',
          'CMP_NAVY18_TRANSFER_BATCH_TITLE':'Transfer batch',
          'CMP_NAVY18_TRANSFER_BATCH_EMPTY':'Transfer basket is empty',
          'CMP_NAVY18_TRANSFER_BATCH_READY':'#P Batch is ready to transfer#!',
          'CMP_NAVY18_TRANSFER_BATCH_INVALID':'#N A basket ship entered battle, became flagship, or is no longer valid#!',
          'CMP_NAVY18_TRANSFER_BATCH_COUNT':'Ships in basket: ',
          'CMP_NAVY18_TRANSFER_CLEAR_BATCH':'Clear basket',
          'CMP_NAVY18_TRANSFER_SINGLE':'TRANSFER EXACT SHIP',
          'CMP_NAVY18_TRANSFER_BATCH':'TRANSFER BASKET',
          'CMP_NAVY18_TRANSFER_SINGLE_TT':'Transfers only the current exact Ship via set_ship_owner. Ships in battle and flagships are blocked.',
          'CMP_NAVY18_TRANSFER_BATCH_ACTION_TT':'Transfers basket ships via set_ship_owner_multiple and then clears the ownership-transfer fleet on the source country as required by Victoria 3 1.13.',
          'CMP_NAVY18_TRANSFER_WARNING':'#Y Ship ownership will change. Verify the marked receiver and basket before executing. Batch transfer clears the source ownership-transfer fleet after the series.#!',
          'CMP_NAVY18_TRANSFER_RESULT_ADDED':'#P Ship added to transfer basket#!',
          'CMP_NAVY18_TRANSFER_RESULT_REMOVED':'#P Ship removed from transfer basket#!',
          'CMP_NAVY18_TRANSFER_RESULT_SINGLE':'#P Exact-ship transfer command completed — verify the receiver fleet#!',
          'CMP_NAVY18_TRANSFER_RESULT_BATCH':'#P Batch transfer completed — verify source and receiver fleets#!',
          'CMP_NAVY18_TRANSFER_RESULT_CLEARED':'Transfer basket cleared',
          'CMP_NAVY18_TRANSFER_SCOPE_NOTE':'beta18 Final: single and batch transfer, cross-Fleet baskets, battle/flagship blocks and ownership-transfer cleanup passed the full regression.'
        }
    for k,v in vals.items(): add(k,v)
    for n in range(1,cfg['transfer']['batch_max']+1): add(f'CMP_NAVY18_TRANSFER_BATCH_COUNT_{n}',f'{n}')
    return '\n'.join(L)+'\n'

def outputs():
    cfg=load(); return {SGUI:generate_sgui(cfg),EFFECT:generate_effects(cfg),LOC_RU:generate_loc(cfg,'russian'),LOC_EN:generate_loc(cfg,'english')}

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); a=ap.parse_args(); stale=[]
    for p,t in outputs().items():
        enc='utf-8-sig'
        if a.check:
            if not p.exists() or p.read_text(encoding=enc)!=t: stale.append(str(p.relative_to(ROOT)))
        else:
            p.parent.mkdir(parents=True,exist_ok=True); p.write_text(t,encoding=enc)
    if a.check:
        if stale: print('STALE: '+', '.join(stale),file=sys.stderr); return 1
        print('PASS: beta18 Final exact ship transfer codegen is deterministic'); return 0
    print('generated beta18 Final transfer SGUI/effects/localization'); return 0
if __name__=='__main__': raise SystemExit(main())
