#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
REG=ROOT/'registry/naval_catalog.json'
SGUI=ROOT/'common/scripted_guis/cmp_navy18_catalog_sgui.txt'
EFFECT=ROOT/'common/scripted_effects/cmp_navy18_catalog_effects.txt'
LOC_RU=ROOT/'localization/russian/cmp_navy18_catalog_l_russian.yml'
LOC_EN=ROOT/'localization/english/cmp_navy18_catalog_l_english.yml'
HEADER='# AUTO-GENERATED by tools/generate_navy18_catalog.py. DO NOT EDIT BY HAND.\n'

def load(): return json.loads(REG.read_text(encoding='utf-8'))
def provider_gate(h): return 'cmp_provider_tech_res_active = yes' if h['provider']=='tech_res' else 'always = yes'
def tech_gate(h): return f"has_technology_researched = {h['unlock_technology']}" if h.get('unlock_technology') else 'always = yes'

def generate_sgui(cfg):
    lines=[HEADER.rstrip(),'# beta18-pre2 full naval catalog: one hull + count -> one NEW fleet using marked owned port HQ.']
    for h in cfg['combat_hulls']:
        sid=h['id']; pg=provider_gate(h); tg=tech_gate(h)
        lines.append(f"cmp_navy18_catalog_{sid}_available = {{ scope = country is_shown = {{ {pg} {tg} }} }}")
        for n in cfg['catalog_amounts']:
            lines.append(f"cmp_navy18_catalog_create_{sid}_{n} = {{ scope = country is_valid = {{ {pg} {tg} any_scope_state = {{ has_decree = decree_sakuya_mark_state owner = root has_port_state = yes }} }} effect = {{ cmp_navy18_catalog_create_{sid}_{n}_effect = yes }} }}")
    lines += [
        'cmp_navy18_catalog_result_created = { scope = country is_shown = { var:cmp_navy18_result = 1 } }',
        'cmp_navy18_catalog_result_failed = { scope = country is_shown = { var:cmp_navy18_result = 2 } }',''
    ]
    return '\n'.join(lines)

def generate_effects(cfg):
    lines=[HEADER.rstrip(),'# Catalog creation intentionally creates a NEW formation and never resolves an existing fleet target.']
    for h in cfg['combat_hulls']:
        sid=h['id']; pg=provider_gate(h); tg=tech_gate(h)
        for n in cfg['catalog_amounts']:
            lines += [
                f'cmp_navy18_catalog_create_{sid}_{n}_effect = {{',
                '    remove_variable = cmp_navy18_result',
                '    cmp_navy18_resolve_hq_effect = yes',
                '    if = {',
                f'        limit = {{ {pg} {tg} exists = scope:cmp_navy18_hq_region }}',
                '        create_military_formation = {',
                '            type = fleet',
                '            hq_region = scope:cmp_navy18_hq_region',
                f'            ship = {{ type = ship_type:{h["ship_type"]} count = {n} }}',
                '        }',
                '        set_variable = { name = cmp_navy18_result value = 1 }',
                '    }',
                '    if = { limit = { NOT = { var:cmp_navy18_result = 1 } } set_variable = { name = cmp_navy18_result value = 2 } }',
                '}',
            ]
    lines.append('')
    return '\n'.join(lines)

def generate_loc(cfg,lang):
    ru=lang=='russian'; L=['l_russian:' if ru else 'l_english:']
    def add(k,v): L.append(f' {k}:0 "{v}"')
    if ru:
        add('CMP_NAVY18_MODE_CATALOG','КАТАЛОГ'); add('CMP_NAVY18_MODE_COMPOSER','КОНСТРУКТОР')
        add('CMP_NAVY18_CATALOG_TITLE','Полный каталог кораблей 1.13')
        add('CMP_NAVY18_CATALOG_DESC','Выберите корпус и количество, чтобы создать отдельный новый флот в отмеченной собственной портовой области. Для кастомизации шаблонов используйте штатный Конструктор кораблей Victoria 3.')
        add('CMP_NAVY18_CATALOG_DESIGNER','ОТКРЫТЬ КОНСТРУКТОР КОРАБЛЕЙ')
        add('CMP_NAVY18_CATALOG_DESIGNER_TT','Открывает штатный Ship Designer. CMP не дублирует и не подменяет создание/редактирование шаблонов кораблей.')
        add('CMP_NAVY18_CATALOG_NO_DLC','Штатный редактор шаблонов доступен при наличии функции Ship Designer; базовые шаблоны по-прежнему используются игрой.')
        add('CMP_NAVY18_CATALOG_GROUPS','Категория корпусов')
        add('CMP_NAVY18_CAT_ALL','Все'); add('CMP_NAVY18_CAT_CAPITAL','Крупные'); add('CMP_NAVY18_CAT_CRUISER','Крейсеры'); add('CMP_NAVY18_CAT_TORPEDO','Торпедные'); add('CMP_NAVY18_CAT_TECH_RES','Tech & Res')
        add('CMP_NAVY18_SHOW_OBSOLETE','Показывать устаревшие'); add('CMP_NAVY18_HIDE_OBSOLETE','Скрывать устаревшие')
        add('CMP_NAVY18_SHOW_OBSOLETE_TT','По умолчанию устаревшие vanilla-корпуса скрываются по фактическому ShipType.IsObsolete для текущей страны. Включите, чтобы видеть полную технологическую линейку.')
        add('CMP_NAVY18_CATALOG_AMOUNT','Создать:')
        add('CMP_NAVY18_CATALOG_LOCKED','технология закрыта')
        add('CMP_NAVY18_CATALOG_READY','доступен')
        add('CMP_NAVY18_CATALOG_CREATE_TT','Создаёт новый отдельный флот с указанным числом кораблей этого корпуса. Existing Fleet target не используется.')
        add('CMP_NAVY18_CATALOG_DEFAULT_TEMPLATE','Создание через scripting использует штатный/default template корпуса. Выбор конкретного пользовательского Ship Template переносится в Fleet Composer 2.0 после отдельного runtime/discovery gate.')
        add('CMP_NAVY18_SUPPLY_TITLE','Суда снабжения')
        add('CMP_NAVY18_SUPPLY_READONLY','#Y Судно снабжения: READ-ONLY в pre2. Назначение/строительство будет включено только после отдельного аудита workflow.#!')
        add('CMP_NAVY18_COMPOSER_COMPAT_TITLE','Смешанный конструктор Tech & Res (совместимость pre1)')
        add('CMP_NAVY18_COMPOSER_COMPAT_DESC','Проверенный pre1-конструктор остаётся доступным как совместимый режим: пять современных типов с независимыми количествами → одна formation. Универсальный 25-корпусный Fleet Composer 2.0 будет следующим этапом.')
    else:
        add('CMP_NAVY18_MODE_CATALOG','CATALOG'); add('CMP_NAVY18_MODE_COMPOSER','COMPOSER')
        add('CMP_NAVY18_CATALOG_TITLE','Full 1.13 Ship Catalog')
        add('CMP_NAVY18_CATALOG_DESC','Choose a hull and amount to create a separate new fleet in a marked owned port state. Use Victoria 3 native Ship Designer for template customization.')
        add('CMP_NAVY18_CATALOG_DESIGNER','OPEN SHIP DESIGNER'); add('CMP_NAVY18_CATALOG_DESIGNER_TT','Opens the native Ship Designer. CMP does not duplicate or replace ship-template creation/editing.')
        add('CMP_NAVY18_CATALOG_NO_DLC','The native template editor requires the Ship Designer feature; the game still uses its base/default templates.')
        add('CMP_NAVY18_CATALOG_GROUPS','Hull category')
        add('CMP_NAVY18_CAT_ALL','All'); add('CMP_NAVY18_CAT_CAPITAL','Capital'); add('CMP_NAVY18_CAT_CRUISER','Cruisers'); add('CMP_NAVY18_CAT_TORPEDO','Torpedo'); add('CMP_NAVY18_CAT_TECH_RES','Tech & Res')
        add('CMP_NAVY18_SHOW_OBSOLETE','Show obsolete'); add('CMP_NAVY18_HIDE_OBSOLETE','Hide obsolete')
        add('CMP_NAVY18_SHOW_OBSOLETE_TT','Obsolete vanilla hulls are hidden by default using ShipType.IsObsolete for the current country. Enable this to see the full technology progression.')
        add('CMP_NAVY18_CATALOG_AMOUNT','Create:'); add('CMP_NAVY18_CATALOG_LOCKED','technology locked'); add('CMP_NAVY18_CATALOG_READY','available')
        add('CMP_NAVY18_CATALOG_CREATE_TT','Creates a separate new fleet with the selected number of this hull. The Existing Fleet target is never used.')
        add('CMP_NAVY18_CATALOG_DEFAULT_TEMPLATE','Scripting creation uses the normal/default template for the hull. Selecting a specific user Ship Template is deferred to Fleet Composer 2.0 after a separate runtime/discovery gate.')
        add('CMP_NAVY18_SUPPLY_TITLE','Supply ships'); add('CMP_NAVY18_SUPPLY_READONLY','#Y Supply Ship is READ-ONLY in pre2. Assignment/construction is gated behind a separate workflow audit.#!')
        add('CMP_NAVY18_COMPOSER_COMPAT_TITLE','Tech & Res Mixed Composer (pre1 compatibility)')
        add('CMP_NAVY18_COMPOSER_COMPAT_DESC','The verified pre1 composer remains available as a compatibility mode: five modern hulls with independent counts → one formation. The universal 25-hull Fleet Composer 2.0 is the next phase.')
    for n in cfg['catalog_amounts']: add(f'CMP_NAVY18_CATALOG_COUNT_{n}',f'x{n}')
    for h in cfg['combat_hulls']+cfg.get('supply_ships',[]):
        key=h['id'].upper(); name=h['name_ru'] if ru else h['name_en']; add(f'CMP_NAVY18_HULL_{key}',name)
        tech=h.get('unlock_technology') or ('базовый корпус' if ru else 'baseline hull')
        group=h['group']; provider=h['provider']
        if ru: add(f'CMP_NAVY18_HULL_{key}_TT',f"{name} · группа: {group} · провайдер: {provider} · технология: {tech}.")
        else: add(f'CMP_NAVY18_HULL_{key}_TT',f"{name} · group: {group} · provider: {provider} · technology: {tech}.")
    return '\n'.join(L)+'\n'

def outputs():
    cfg=load(); return {SGUI:generate_sgui(cfg),EFFECT:generate_effects(cfg),LOC_RU:generate_loc(cfg,'russian'),LOC_EN:generate_loc(cfg,'english')}
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); args=ap.parse_args(); stale=[]
    for p,t in outputs().items():
        enc='utf-8-sig'
        if args.check:
            if not p.exists() or p.read_text(encoding=enc)!=t: stale.append(str(p.relative_to(ROOT)))
        else:
            p.parent.mkdir(parents=True,exist_ok=True); p.write_text(t,encoding=enc)
    if args.check:
        if stale: print('STALE: '+', '.join(stale),file=sys.stderr); return 1
        print('PASS: beta18-pre2 full naval catalog codegen is deterministic'); return 0
    print('generated beta18-pre2 catalog SGUI/effects/localization'); return 0
if __name__=='__main__': raise SystemExit(main())
