#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
REG=ROOT/'registry/staffing.json'
SGUI=ROOT/'common/scripted_guis/cmp_staffing_sgui.txt'
EFFECT=ROOT/'common/scripted_effects/cmp_staffing_effects.txt'
HEADER='# AUTO-GENERATED by tools/generate_staffing2.py. DO NOT EDIT BY HAND.'
AMOUNTS=[1000,5000,10000,25000,50000,100000]
RELIGIONS=['catholic','protestant','orthodox','oriental_orthodox','sunni','shiite','ibadi','jewish','mahayana','gelugpa','theravada','confucian','hindu','shinto','sikh','animist','atheist']

def load(): return json.loads(REG.read_text(encoding='utf-8'))
def supported(data): return [x for x in data['buildings'] if x['status']=='SUPPORTED']
def new_any(entries): return 'OR = { ' + ' '.join(f"has_variable = {e['selection_variable']}" for e in entries) + ' }'
def selector(e, *, include_legacy=True):
    bits=[f"has_variable = {e['selection_variable']}"]
    if include_legacy and e.get('legacy_selection_variable'): bits.append(f"has_variable = {e['legacy_selection_variable']}")
    return bits[0] if len(bits)==1 else 'OR = { '+' '.join(bits)+' }'

def gen_sgui(data):
    entries=supported(data); any_new=new_any(entries)
    L=[HEADER,'# Staffing Coverage 2.1: independent Workspace selection + legacy fallback.']
    L.append(f"cmp_staffing_workspace_selection_ready = {{ scope = country is_shown = {{ {any_new} }} }}")
    all_sel=[]
    for e in entries: all_sel += [f"has_variable = {e['selection_variable']}"] + ([f"has_variable = {e['legacy_selection_variable']}"] if e.get('legacy_selection_variable') else [])
    L.append('cmp_staffing_supported_building_check = { scope = country is_shown = { OR = { '+' '.join(all_sel)+' } } }')
    for e in entries:
        L.append(f"cmp_staffing_workspace_{e['id']}_selected = {{ scope = country is_shown = {{ has_variable = {e['selection_variable']} }} }}")
        gate='cmp_provider_tech_res_active = yes' if e['provider']=='tech_res' else 'always = yes'
        L.append(f"cmp_staffing_select_{e['id']} = {{ scope = country is_valid = {{ {gate} }} effect = {{ cmp_staffing_select_{e['id']}_effect = yes }} }}")
    for pid in data['profiles']:
        items=[e for e in entries if e['profile']==pid]
        if not items: continue
        new=' '.join(f"has_variable = {e['selection_variable']}" for e in items)
        legacy=' '.join(f"has_variable = {e['legacy_selection_variable']}" for e in items if e.get('legacy_selection_variable'))
        body=f"OR = {{ {new}"
        if legacy: body += f" AND = {{ NOT = {{ {any_new} }} OR = {{ {legacy} }} }}"
        body += ' }'
        L.append(f"cmp_staffing_profile_{pid}_check = {{ scope = country is_shown = {{ {body} }} }}")
    L.append('cmp_staffing_amount_selected_check = { scope = country is_shown = { has_variable = cmp_staffing_amount_index } }')
    for i,a in enumerate(AMOUNTS,1):
        L.append(f"cmp_staffing_amount_{a}_selected_check = {{ scope = country is_shown = {{ has_variable = cmp_staffing_amount_index var:cmp_staffing_amount_index = {i} }} }}")
    # Compatibility checks used by the hidden legacy B6 staffing panel.
    def matching_state(e,kind):
        sel=selector(e)
        bt=e['building_type']
        if kind=='marked': return f"AND = {{ {sel} any_scope_state = {{ has_decree = decree_sakuya_mark_state any_scope_building = {{ is_building_type = {bt} }} }} }}"
        if kind=='incorp': return f"AND = {{ {sel} any_scope_state = {{ is_incorporated = yes any_scope_building = {{ is_building_type = {bt} }} }} }}"
        return f"AND = {{ {sel} any_state = {{ has_variable = sakuya_mark_foreign_state_target owner = {{ has_variable = sakuya_mark_country_target }} any_scope_building = {{ is_building_type = {bt} }} }} }}"
    for name,kind in [('cmp_staffing_can_player_marked_check','marked'),('cmp_staffing_can_player_incorporated_check','incorp'),('cmp_staffing_can_marked_country_check','foreign')]:
        body=' '.join(matching_state(e,kind) for e in entries)
        L.append(f"{name} = {{ scope = country is_shown = {{ has_variable = cmp_staffing_amount_index OR = {{ {body} }} }} }}")
    for a in AMOUNTS:
        L.append(f"cmp_staffing_select_amount_{a} = {{ scope = country is_shown = {{ is_player = yes }} effect = {{ cmp_staffing_select_amount_{a}_effect = yes }} }}")
    L += [
      "cmp_staffing_clear_selection = { scope = country is_valid = { always = yes } effect = { cmp_staffing_clear_selection_effect = yes } }",
      "cmp_staffing_apply_player_marked = { scope = country is_shown = { is_player = yes } effect = { cmp_staffing_dispatch_player_marked_effect = yes } }",
      "cmp_staffing_apply_player_incorporated = { scope = country is_shown = { is_player = yes } effect = { cmp_staffing_dispatch_incorporated_effect = yes } }",
      "cmp_staffing_apply_marked_country = { scope = country is_shown = { is_player = yes } effect = { cmp_staffing_dispatch_foreign_effect = yes } }",
      ''
    ]
    return '\n'.join(L)

def gen_effect(data):
    entries=supported(data); any_new=new_any(entries)
    L=[HEADER,'# Staffing Coverage 2.1 deterministic workforce reserves.']
    L += [
      'cmp_staffing_clear_runtime_effect = {',
      '  clear_saved_scope = cmp_staffing_owner_country',
      '  clear_saved_scope = cmp_staffing_target_culture',
      '}',
      'cmp_staffing_resolve_state_owner_effect = {',
      '  cmp_staffing_clear_runtime_effect = yes',
      '  owner = { save_scope_as = cmp_staffing_owner_country ordered_primary_culture = { position = 0 check_range_bounds = no save_scope_as = cmp_staffing_target_culture } }',
      '}',
      'cmp_staffing_create_cohort_effect = {',
      '  cmp_staffing_resolve_state_owner_effect = yes',
    ]
    for rel in RELIGIONS:
        L.append(f"  if = {{ limit = {{ exists = scope:cmp_staffing_owner_country scope:cmp_staffing_owner_country = {{ country_has_state_religion = rel:{rel} }} }} create_pop = {{ pop_type = $TYPE$ religion = {rel} culture = sakuya_nonexistent size = $SIZE$ working_adult_ratio = 1.0 }} }}")
    L += [
      '  if = { limit = { exists = scope:cmp_staffing_target_culture } every_scope_pop = { limit = { culture = cu:sakuya_nonexistent } set_pop_literacy = { literacy_rate = 0.8 } set_pop_qualifications = { pop_type = $TYPE$ qualifications = 1.0 } change_pop_culture = { value = 1 target = scope:cmp_staffing_target_culture } } if = { limit = { NOT = { has_cultural_community = scope:cmp_staffing_target_culture } } add_cultural_community = scope:cmp_staffing_target_culture } }',
      '  cmp_staffing_clear_runtime_effect = yes',
      '}',
    ]
    for pid,p in data['profiles'].items():
        L.append(f"cmp_staffing_spawn_{pid}_profile_effect = {{")
        for idx,amount in enumerate(AMOUNTS,1):
            L.append(f"  if = {{ limit = {{ root.var:cmp_staffing_amount_index = {idx} }}")
            for pop,weight in p['weights'].items():
                size=amount*weight//1000
                if size: L.append(f"    cmp_staffing_create_cohort_effect = {{ TYPE = {pop} SIZE = {size} }}")
            L.append('  }')
        L.append('}')
    L.append('cmp_staffing_apply_hiring_boost_for_type_effect = { every_scope_building = { limit = { is_building_type = $BUILDING$ } remove_modifier = cmp_staffing_hiring_boost add_modifier = { name = cmp_staffing_hiring_boost days = 30 } } }')
    # Independent Workspace selector: clear only Staffing 2.1 markers, never the building-operations variables.
    L.append('cmp_staffing_clear_selection_effect = {')
    for e in entries: L.append(f"  remove_variable = {e['selection_variable']}")
    L.append('  cmp_staffing_clear_result_effect = yes')
    L.append('}')
    for e in entries:
        L.append(f"cmp_staffing_select_{e['id']}_effect = {{ cmp_staffing_clear_selection_effect = yes set_variable = {{ name = {e['selection_variable']} value = 1 }} }}")
    # Application prefers the new independent selector; legacy B6 markers are fallback only when no new marker exists.
    L.append('cmp_staffing_apply_current_state_effect = {')
    L.append(f"  if = {{ limit = {{ root = {{ {any_new} }} }}")
    for e in entries:
        L.append(f"    if = {{ limit = {{ root = {{ has_variable = {e['selection_variable']} }} any_scope_building = {{ is_building_type = {e['building_type']} }} }} cmp_staffing_spawn_{e['profile']}_profile_effect = yes cmp_staffing_apply_hiring_boost_for_type_effect = {{ BUILDING = {e['building_type']} }} }}")
    L.append('  }')
    legacy=[e for e in entries if e.get('legacy_selection_variable')]
    L.append('  else = {')
    for e in legacy:
        L.append(f"    if = {{ limit = {{ root = {{ has_variable = {e['legacy_selection_variable']} }} any_scope_building = {{ is_building_type = {e['building_type']} }} }} cmp_staffing_spawn_{e['profile']}_profile_effect = yes cmp_staffing_apply_hiring_boost_for_type_effect = {{ BUILDING = {e['building_type']} }} }}")
    L.append('  }')
    L.append('}')
    # Legacy direct dispatch effects retained for source fallback compatibility.
    L += [
      'cmp_staffing_apply_player_marked_states_effect = { if = { limit = { has_variable = cmp_staffing_amount_index any_scope_state = { has_decree = decree_sakuya_mark_state } } every_scope_state = { limit = { has_decree = decree_sakuya_mark_state } cmp_staffing_apply_current_state_effect = yes } } }',
      'cmp_staffing_apply_player_incorporated_states_effect = { if = { limit = { has_variable = cmp_staffing_amount_index any_scope_state = { is_incorporated = yes } } every_scope_state = { limit = { is_incorporated = yes } cmp_staffing_apply_current_state_effect = yes } } }',
      'cmp_staffing_apply_marked_country_states_effect = { sakuya_b6_resolve_marked_country_effect = yes if = { limit = { has_variable = cmp_staffing_amount_index exists = scope:sakuya_b6_marked_country_scope any_state = { has_variable = sakuya_mark_foreign_state_target owner = scope:sakuya_b6_marked_country_scope } } scope:sakuya_b6_marked_country_scope = { every_scope_state = { limit = { has_variable = sakuya_mark_foreign_state_target } cmp_staffing_apply_current_state_effect = yes } } } }',
      '# Amount selection'
    ]
    for idx,a in enumerate(AMOUNTS,1): L.append(f"cmp_staffing_select_amount_{a}_effect = {{ set_variable = {{ name = cmp_staffing_amount_index value = {idx} }} }}")
    L.append('cmp_staffing_clear_amount_effect = { remove_variable = cmp_staffing_amount_index }')
    L.append('')
    return '\n'.join(L)

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); args=ap.parse_args()
    data=load(); expected={SGUI:gen_sgui(data),EFFECT:gen_effect(data)}
    if args.check:
        stale=[str(p.relative_to(ROOT)) for p,t in expected.items() if not p.exists() or p.read_text(encoding='utf-8-sig')!=t]
        if stale: print('STALE: '+', '.join(stale),file=sys.stderr); return 1
        print('PASS: Staffing Coverage 2.1 artifacts are deterministic'); return 0
    for p,t in expected.items(): p.write_text(t,encoding='utf-8-sig' if p==SGUI else 'utf-8')
    print(f"generated {len(supported(data))} supported staffing entries across {len(data['profiles'])} profiles")
    return 0
if __name__=='__main__': raise SystemExit(main())
