#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
REG=ROOT/'registry/navy18.json'
SGUI=ROOT/'common/scripted_guis/cmp_navy18_logistics_sgui.txt'
EFFECT=ROOT/'common/scripted_effects/cmp_navy18_logistics_effects.txt'
LOC_RU=ROOT/'localization/russian/cmp_navy18_logistics_l_russian.yml'
LOC_EN=ROOT/'localization/english/cmp_navy18_logistics_l_english.yml'
HEADER='# AUTO-GENERATED by tools/generate_navy18_logistics.py. DO NOT EDIT BY HAND.\n'


def load():
    return json.loads(REG.read_text(encoding='utf-8'))


def generate_sgui(cfg:dict)->str:
    amounts=cfg['naval_logistics']['supply_add_amounts']
    L=[HEADER.rstrip(),
       '# beta18 Final Retrofit bridge + national Supply Ship reserve writes + selected-formation assigned-supply diagnostics.',
       '# num_assigned_supply_ships is a 1.13.9 value event target on military_formation; add_supply_ships is a 1.13 country effect.']
    # Country-scope reserve writes and feedback.
    for n in amounts:
        L.append(f'cmp_navy18_supply_add_{n} = {{ scope = country is_valid = {{ is_player = yes }} effect = {{ cmp_navy18_supply_add_{n}_effect = yes }} }}')
        L.append(f'cmp_navy18_supply_result_{n} = {{ scope = country is_shown = {{ var:cmp_navy18_supply_last_add = {n} }} }}')
    L += [
      'cmp_navy18_supply_maintenance_good = { scope = country is_shown = { supply_ship_maintenance_fulfillment >= 0.75 } }',
      'cmp_navy18_supply_maintenance_medium = { scope = country is_shown = { supply_ship_maintenance_fulfillment >= 0.25 supply_ship_maintenance_fulfillment < 0.75 } }',
      'cmp_navy18_supply_maintenance_bad = { scope = country is_shown = { supply_ship_maintenance_fulfillment < 0.25 } }',
      # Formation diagnostics. Deliberately no write/assignment action: only the documented assigned count is read.
      'cmp_navy18_supply_assigned_0 = { scope = military_formation is_shown = { num_assigned_supply_ships = 0 } }',
      'cmp_navy18_supply_assigned_1 = { scope = military_formation is_shown = { num_assigned_supply_ships = 1 } }',
      'cmp_navy18_supply_assigned_2 = { scope = military_formation is_shown = { num_assigned_supply_ships = 2 } }',
      'cmp_navy18_supply_assigned_3 = { scope = military_formation is_shown = { num_assigned_supply_ships = 3 } }',
      'cmp_navy18_supply_assigned_4 = { scope = military_formation is_shown = { num_assigned_supply_ships = 4 } }',
      'cmp_navy18_supply_assigned_5 = { scope = military_formation is_shown = { num_assigned_supply_ships = 5 } }',
      'cmp_navy18_supply_assigned_6_10 = { scope = military_formation is_shown = { num_assigned_supply_ships >= 6 num_assigned_supply_ships <= 10 } }',
      'cmp_navy18_supply_assigned_11_20 = { scope = military_formation is_shown = { num_assigned_supply_ships >= 11 num_assigned_supply_ships <= 20 } }',
      'cmp_navy18_supply_assigned_21_50 = { scope = military_formation is_shown = { num_assigned_supply_ships >= 21 num_assigned_supply_ships <= 50 } }',
      'cmp_navy18_supply_assigned_51_plus = { scope = military_formation is_shown = { num_assigned_supply_ships >= 51 } }',
      ''
    ]
    return '\n'.join(L)


def generate_effects(cfg:dict)->str:
    amounts=cfg['naval_logistics']['supply_add_amounts']
    L=[HEADER.rstrip(),
       '# Public 1.13 contract: add_supply_ships adds Supply Ships to the scoped country.',
       '# No direct formation assignment or direct ShipTemplate/retrofit write is invented in this file.']
    for n in amounts:
        L += [
          f'cmp_navy18_supply_add_{n}_effect = {{',
          '    remove_variable = cmp_navy18_supply_last_add',
          f'    add_supply_ships = {{ value = {n} }}',
          f'    set_variable = {{ name = cmp_navy18_supply_last_add value = {n} }}',
          '}',
        ]
    L.append('')
    return '\n'.join(L)


def generate_loc(cfg:dict,lang:str)->str:
    ru=lang=='russian'; L=['l_russian:' if ru else 'l_english:']; add=lambda k,v:L.append(f' {k}:0 "{v}"')
    if ru:
        vals={
          'CMP_NAVY18_MODE_LOGISTICS':'ЛОГИСТИКА',
          'CMP_NAVY18_LOGISTICS_TITLE':'Модернизация и морская логистика',
          'CMP_NAVY18_LOGISTICS_DESC':'Шаблоны и модернизация остаются штатной механикой Victoria 3. CMP открывает родной конструктор и карточку выбранного флота, но не подменяет выбор шаблона. Ниже можно мгновенно пополнить государственный резерв судов снабжения.',
          'CMP_NAVY18_RETROFIT_TITLE':'Шаблоны и модернизация',
          'CMP_NAVY18_RETROFIT_STATUS':'#P Native bridge готов#! — пользовательские шаблоны создаются в штатном Конструкторе кораблей; модернизация выполняется через штатный список кораблей/выбор шаблона.',
          'CMP_NAVY18_RETROFIT_OPEN_DESIGNER':'ОТКРЫТЬ КОНСТРУКТОР КОРАБЛЕЙ',
          'CMP_NAVY18_RETROFIT_OPEN_DESIGNER_TT':'Открывает штатный Ship Designer Victoria 3. Создайте или измените пользовательский шаблон нужного типа корабля.',
          'CMP_NAVY18_RETROFIT_OPEN_FLEET':'ОТКРЫТЬ ШТАТНУЮ КАРТОЧКУ ФЛОТА',
          'CMP_NAVY18_RETROFIT_OPEN_FLEET_TT':'Открывает выбранный флот штатным интерфейсом Victoria 3. Далее используйте редактирование списка кораблей → изменить шаблон → модернизировать.',
          'CMP_NAVY18_RETROFIT_SELECT_FLEET':'#N Сначала выберите флот, если хотите перейти к его модернизации#!',
          'CMP_NAVY18_RETROFIT_FLOW':'Маршрут: 1) создать/изменить шаблон → 2) открыть нужный флот → 3) выбрать корабли → 4) изменить шаблон → 5) модернизировать. CMP не вызывает RetrofitShips напрямую, пока не доказано безопасное связывание exact Ship CMP с native ShipSelection.',
          'CMP_NAVY18_SUPPLY_RESERVE_TITLE':'Государственный резерв судов снабжения',
          'CMP_NAVY18_SUPPLY_RESERVE_DESC':'Эти кнопки изменяют резерв судов снабжения всей державы, а не состав конкретного флота. Используется документированный country-effect add_supply_ships.',
          'CMP_NAVY18_SUPPLY_MAINT_TITLE':'Обеспечение судов снабжения',
          'CMP_NAVY18_SUPPLY_MAINT_GOOD':'#P Обеспечение судов снабжения: высокое (75%+)#!',
          'CMP_NAVY18_SUPPLY_MAINT_MEDIUM':'#Y Обеспечение судов снабжения: среднее (25–74%)#!',
          'CMP_NAVY18_SUPPLY_MAINT_BAD':'#N Обеспечение судов снабжения: низкое (<25%)#!',
          'CMP_NAVY18_SUPPLY_ADD_TT':'Добавляет указанное количество судов снабжения в государственный резерв. Это чит-действие и не назначает суда конкретному формированию напрямую.',
          'CMP_NAVY18_SUPPLY_SELECTED_TITLE':'Снабжение выбранного формирования',
          'CMP_NAVY18_SUPPLY_SELECTED_DESC':'Victoria 3 1.13.9 предоставляет num_assigned_supply_ships для MilitaryFormation. CMP показывает назначенное количество только как диагностику; прямую команду назначения судов формированию мы не придумываем.',
          'CMP_NAVY18_SUPPLY_NO_FLEET':'Флот не выбран — диагностика назначенных судов снабжения недоступна',
          'CMP_NAVY18_SUPPLY_ASSIGNED_LABEL':'Назначено выбранному формированию:',
          'CMP_NAVY18_SUPPLY_ASSIGNED_0':'0', 'CMP_NAVY18_SUPPLY_ASSIGNED_1':'1', 'CMP_NAVY18_SUPPLY_ASSIGNED_2':'2', 'CMP_NAVY18_SUPPLY_ASSIGNED_3':'3', 'CMP_NAVY18_SUPPLY_ASSIGNED_4':'4', 'CMP_NAVY18_SUPPLY_ASSIGNED_5':'5',
          'CMP_NAVY18_SUPPLY_ASSIGNED_6_10':'6–10', 'CMP_NAVY18_SUPPLY_ASSIGNED_11_20':'11–20', 'CMP_NAVY18_SUPPLY_ASSIGNED_21_50':'21–50', 'CMP_NAVY18_SUPPLY_ASSIGNED_51_PLUS':'51+',
          'CMP_NAVY18_SUPPLY_RESULT_PREFIX':'Последняя операция CMP:',
          'CMP_NAVY18_SUPPLY_RESULT_1':'#P +1 судно снабжения#!', 'CMP_NAVY18_SUPPLY_RESULT_10':'#P +10 судов снабжения#!', 'CMP_NAVY18_SUPPLY_RESULT_50':'#P +50 судов снабжения#!', 'CMP_NAVY18_SUPPLY_RESULT_100':'#P +100 судов снабжения#!',
          'CMP_NAVY18_LOGISTICS_SCOPE_NOTE':'beta18 Final: нативный маршрут модернизации и морская логистика подтверждены полным regression. Десантный помощник остаётся после beta18 Final; неподтверждённые прямые записи ShipTemplate не используются.'
        }
    else:
        vals={
          'CMP_NAVY18_MODE_LOGISTICS':'LOGISTICS',
          'CMP_NAVY18_LOGISTICS_TITLE':'Retrofit and Naval Logistics',
          'CMP_NAVY18_LOGISTICS_DESC':'Templates and retrofit remain native Victoria 3 mechanics. CMP opens the native designer and selected fleet panel without replacing template selection. The lower section can instantly add Supply Ships to the national reserve.',
          'CMP_NAVY18_RETROFIT_TITLE':'Templates and retrofit',
          'CMP_NAVY18_RETROFIT_STATUS':'#P Native bridge ready#! — user templates are created in the native Ship Designer and retrofit is performed through the native ship list/template workflow.',
          'CMP_NAVY18_RETROFIT_OPEN_DESIGNER':'OPEN SHIP DESIGNER',
          'CMP_NAVY18_RETROFIT_OPEN_DESIGNER_TT':'Opens Victoria 3 native Ship Designer. Create or edit a user template for the required ship type.',
          'CMP_NAVY18_RETROFIT_OPEN_FLEET':'OPEN NATIVE FLEET PANEL',
          'CMP_NAVY18_RETROFIT_OPEN_FLEET_TT':'Opens the selected fleet in Victoria 3 native UI. Continue with ship-list editing → change template → retrofit.',
          'CMP_NAVY18_RETROFIT_SELECT_FLEET':'#N Select a fleet first to continue to its native retrofit workflow#!',
          'CMP_NAVY18_RETROFIT_FLOW':'Route: 1) create/edit template → 2) open target fleet → 3) select ships → 4) change template → 5) retrofit. CMP does not call RetrofitShips directly until exact CMP Ship ↔ native ShipSelection binding is proven safe.',
          'CMP_NAVY18_SUPPLY_RESERVE_TITLE':'National Supply Ship reserve',
          'CMP_NAVY18_SUPPLY_RESERVE_DESC':'These actions modify the country-wide Supply Ship reserve, not the composition of a specific fleet. They use the documented country effect add_supply_ships.',
          'CMP_NAVY18_SUPPLY_MAINT_TITLE':'Supply Ship maintenance',
          'CMP_NAVY18_SUPPLY_MAINT_GOOD':'#P Supply Ship maintenance fulfillment: high (75%+)#!',
          'CMP_NAVY18_SUPPLY_MAINT_MEDIUM':'#Y Supply Ship maintenance fulfillment: medium (25–74%)#!',
          'CMP_NAVY18_SUPPLY_MAINT_BAD':'#N Supply Ship maintenance fulfillment: low (<25%)#!',
          'CMP_NAVY18_SUPPLY_ADD_TT':'Adds the selected number of Supply Ships to the national reserve. This is a cheat action and does not directly assign ships to a formation.',
          'CMP_NAVY18_SUPPLY_SELECTED_TITLE':'Selected formation supply',
          'CMP_NAVY18_SUPPLY_SELECTED_DESC':'Victoria 3 1.13.9 exposes num_assigned_supply_ships for MilitaryFormation. CMP reads it for diagnostics only; no unproven formation-assignment command is invented.',
          'CMP_NAVY18_SUPPLY_NO_FLEET':'No fleet selected — assigned Supply Ship diagnostics unavailable',
          'CMP_NAVY18_SUPPLY_ASSIGNED_LABEL':'Assigned to selected formation:',
          'CMP_NAVY18_SUPPLY_ASSIGNED_0':'0', 'CMP_NAVY18_SUPPLY_ASSIGNED_1':'1', 'CMP_NAVY18_SUPPLY_ASSIGNED_2':'2', 'CMP_NAVY18_SUPPLY_ASSIGNED_3':'3', 'CMP_NAVY18_SUPPLY_ASSIGNED_4':'4', 'CMP_NAVY18_SUPPLY_ASSIGNED_5':'5',
          'CMP_NAVY18_SUPPLY_ASSIGNED_6_10':'6–10', 'CMP_NAVY18_SUPPLY_ASSIGNED_11_20':'11–20', 'CMP_NAVY18_SUPPLY_ASSIGNED_21_50':'21–50', 'CMP_NAVY18_SUPPLY_ASSIGNED_51_PLUS':'51+',
          'CMP_NAVY18_SUPPLY_RESULT_PREFIX':'Last CMP operation:',
          'CMP_NAVY18_SUPPLY_RESULT_1':'#P +1 Supply Ship#!', 'CMP_NAVY18_SUPPLY_RESULT_10':'#P +10 Supply Ships#!', 'CMP_NAVY18_SUPPLY_RESULT_50':'#P +50 Supply Ships#!', 'CMP_NAVY18_SUPPLY_RESULT_100':'#P +100 Supply Ships#!',
          'CMP_NAVY18_LOGISTICS_SCOPE_NOTE':'beta18 Final: the native retrofit route and naval logistics passed the full regression. Amphibious Assistant remains post-beta18 Final, and no unproven direct ShipTemplate writes are used.'
        }
    for k,v in vals.items(): add(k,v)
    for n in cfg['naval_logistics']['supply_add_amounts']:
        add(f'CMP_NAVY18_SUPPLY_ADD_{n}',f'+{n}')
    return '\n'.join(L)+'\n'


def outputs():
    cfg=load()
    return {SGUI:generate_sgui(cfg),EFFECT:generate_effects(cfg),LOC_RU:generate_loc(cfg,'russian'),LOC_EN:generate_loc(cfg,'english')}


def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); a=ap.parse_args(); stale=[]
    for p,t in outputs().items():
        enc='utf-8-sig'
        if a.check:
            if not p.exists() or p.read_text(encoding=enc)!=t: stale.append(str(p.relative_to(ROOT)))
        else:
            p.parent.mkdir(parents=True,exist_ok=True); p.write_text(t,encoding=enc)
    if a.check:
        if stale:
            print('STALE: '+', '.join(stale),file=sys.stderr); return 1
        print('PASS: beta18 Final retrofit/logistics codegen is deterministic'); return 0
    print('generated beta18 Final retrofit/logistics SGUI/effects/localization'); return 0

if __name__=='__main__':
    raise SystemExit(main())
